### ISSUE TITLE
Lieferplanung enthält Lieferungen mit unterschiedlichen Daten: Lieferantenzusammenfassung fehlerhaft

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#109]
**Problem beschreiben / Describe the bug**

Wenn eine Lieferplanung Lieferungen mit unterschiedlichen Daten enthält, ist die Lieferantenzusammenfassung fehlerhaft.

Es erscheinen nur Produkte eines Liefer-Datums.

**Problem reproduzieren / To Reproduce**

Regioterre LP #204.

**Comment by mcmpp** [comment]
merged in prod
