### ISSUE TITLE
Test der Backend-Erweiterung im Branch "dev/upgrade_akka_http"

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#110]
- [x] Grundsätzlicher Zugang zu den Daten mittels Login
- [x] Einfache Modifikation von Daten (Kundendaten, Depot, )
- [x] Komplexer Arbeitsschritt (LP eröffnen, verändern, abschliessen)
- [x] Export von Daten aus Tabelle (CSV)
- [x] Generieren von Reports: ODF, PDF (Rechnungen, Auslieferungen, Etiketten)
- [x] Ablagen der generierten Dokumente (Rechnung)
- [x] Zugriff auf Ablage (Rechnung)
- [x] Zahlungsimport
- [x] Zahlungsauftrag-Export
- [x] Auswertungen
- [x] Journal-Zugriff [bug]
- [x] Report-Vorlagen ablegen/modifizieren [bug]
- [x] Mail-Voralgen anlegen/modifizieren [bug]
- [x] Mail-Versand mit Vorlage
- [x] Kundenportal: Lesen und Abwesenheit eintragen

Getestet auf https://soliterre-test.openolitor.ch/admin/

**Comment by AlwinEgger** [comment]
Bei ganz grossen, zusammengeführten Reports (Etiketten für sehr viele Auslierferungen, 200 oder mehr) crasht der Server zuverlässigerweise...

**Comment by AlwinEgger** [comment]
Problems:

- [x] Journal-Zugriff: Should use `journal_view`
- [x] Report-Vorlagen ablegen/modifizieren: Grund unbekannt
- [x] Mail-Voralgen anlegen/modifizieren: Modul funktioniert u.U. nicht oder anderes Problem

**Comment by rawyler** [comment]
> * [x]  Report-Vorlagen ablegen/modifizieren: Grund unbekannt

uploading on localhost works as expected

editing, uploading a different template seems to work, but creating a new one doesn't

**Comment by rawyler** [comment]
- [x] Kunde erstellen mit einzelner Ansprechperson schlägt fehl mit BadRequest `The request content was malformed: key not found: bezeichnung`

**Comment by rawyler** [comment]
> Bei ganz grossen, zusammengeführten Reports (Etiketten für sehr viele Auslierferungen, 200 oder mehr) crasht der Server zuverlässigerweise...

should work with adjusted `application.conf`

**Comment by AlwinEgger** [comment]
Memory consumption now recovers well, so let's add some power to the cloud environments and set xmx to 6GB (maximum memory server component may use).

![image](https://user-images.githubusercontent.com/4997364/190099010-8a8322da-2a41-4538-b2b6-ac8175daa1da.png)

- [x] We should use application.ini and not a hard coded value to set xmx: https://github.com/OpenOlitor/openolitor-server/pull/647

https://www.scala-sbt.org/sbt-native-packager/archetypes/java_app/customize.html#via-application-ini

**Comment by rawyler** [comment]
- [x] cannot display deliveries in kundenportal
  - [x] java.lang.UnsupportedOperationException: You should call #toOne, #toMany or #toManies here.

**Comment by rawyler** [comment]
![image](https://user-images.githubusercontent.com/96559/194483273-edfb4643-3121-41a9-b643-074c4d439d2c.png)

**Comment by rawyler** [comment]
![image](https://user-images.githubusercontent.com/96559/194487343-52e72822-6d7c-48c2-8e97-01c210580770.png)
