### ISSUE TITLE
Lieferplanung: Berechnung weicht nach Speichern leicht ab

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#111]
Wird eine Lieferplanung erstellt und genaue Werte für Produkte eingetragen, so kann es sein, dass nach dem Speichern diese wieder leicht divergieren.

![image](https://user-images.githubusercontent.com/4997364/190116530-fa369c07-814a-4688-97e5-8fa9b8bb0889.png)

![image](https://user-images.githubusercontent.com/4997364/190116714-f9953674-f6a7-4e96-b667-3e2cb9bde5aa.png)

**Comment by rawyler** [comment]
Client-seitig verwenden wir `ng-pattern="/^[0-9]+([\.,][0-9]{1,3})?$/" min="0" step="0.001"`, was uns erlaubt 3 Nachkommastellen zu verwenden.

Server-seitig, bzw. Datenbank-seitig ist die `menge` auf `Lieferposition` mit `Decimal(7, 2)` definiert, sprich 2 Nachkommastellen.

Wir könnten durchaus die `Scale` auf 3 und die `Precision` entsprechend auf 8 erhöhen um 3 Nachkommastellen bis auf die DB zu erlauben.

@AlwinEgger was denkst Du?

**Comment by AlwinEgger** [comment]
Auf jeden Fall sollte Client und Server die selbe Präzision ermöglichen. Bei KG sind wohl drei Nachkommastellen schon sinnvoll, daher würde ich auf dem Server erhöhen, ja.
