### ISSUE TITLE
Overviews: Search is not working

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#112]
**Problem beschreiben / Describe the bug**
On the Rechnungen-Overview the search is not working. Not for `RechnungId` and not for any other value.

**Screenshots**

Searching by `RechnungId`.

![image](https://user-images.githubusercontent.com/4997364/192234593-75b8a873-a531-4028-92a4-a11e5397f733.png)

**Comment by AlwinEgger** [comment]
This applies for Rechnungen but also on Personen (Kunden-Nr)

**Comment by mcmpp** [comment]
I have added all the ids as a search criteria and in all overviews. I have added some extra parameters for the invoices.

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-client-admin/pull/620
https://github.com/OpenOlitor/openolitor-server/pull/651

**Comment by rawyler** [comment]
java.lang.NumberFormatException: For input string: "Alle"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)

- working when selecting other than `"Alle"`
![image](https://user-images.githubusercontent.com/96559/197154628-86bb340c-2580-4409-83c5-2a608cc4af44.png)

- Selecting `"Alle"` after initial view works as well

**Comment by AlwinEgger** [comment]
Working fine for most Overviews (all important ones, as far as I can see).

Lieferplanung-Overview is not working and adding a search string in the field is causing a server side error.

**Comment by AlwinEgger** [comment]
Works fine. Thanks!
