### ISSUE TITLE
Neue CSA hinzufügen

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#113]
Hey.
Ich wollte jetzt das erste mal ein neues Projekt/CSA hinzufügen. 
Ich nutze die Docker Version und habe dazu meine prod.json um die neue CSA erweitert.
Dann habe ich mir mit der generator.py die Konfig Dateien erstellen lassen und die Conainer neu gestartet.
Eine passenden Sub-Domain habe ich auch erstellt und meinen nginx erweitert.
Die Webseite kann ich erreichen, allerdings wird mir der Websocket nicht geöffnet. In der Konsole von Firefox kommen beim Zugriff auf die /api-[csa]/ Fehler mit "405 Method not Allowed".
Im Log vom Server-Container sehe ich, dass er anscheinend nicht auf die Datenbank zugreifen kann. Wenn ich dann manuell auf die Datendank zugreife, habe ich auch weiterhin nur die Datenbank meiner bestehenden Solawi. Eine neue Datenbank für die neue CSA wurde nicht erstellt.

Hab ich beim erstellen der neuen CSA was falsch gemacht?
Wie sind denn die ersten Zugangsdaten bei einer neuen CSA?

**Comment by AlwinEgger** [comment]
Hallo @budda85 

Wenn von Beginn weg mit mehreren CSAs gestartet wird, dann klappt dies. Dann wird das generierte DB-Schema erstellt. Bei einer zusätzlichen CSA wird das Schema-Script dann aber nicht wieder ausgeführt (mariadb Funktionalität).

So musst du effektiv eine neue Datenbank für die neue Solawi von Hand erstellen. Dazu kannst du [dieses Script](https://github.com/OpenOlitor/openolitor-docker-compose/blob/master/config/db/db_schema.sql) als Basis nehmen und entsprechend anpassen oder du kopierst den zusätzlichen Teil im bei dir generierten Script.

Das musst du dann als DB-Admin ausführen und den Server neu starten.

**Comment by budda85** [comment]
Hi @AlwinEgger 
Ich habe das Script jetzt mit der Datenbank, dem User und dem Passwort angepasst und ausgeführt auf der Datenbank.
Dann wird mir ja die Datenbank erstellt, der User mit passenden Privilegien angelegt und 5 Tabellen angelegt.
Dann habe ich die Container neu gestartet. Jetzt fängt OO an die Datenbank mit Tabellen zu füllen.
Mein Websocket Problem besteht weiterhin und es fehlen mir Tabellen in der Datenbank wie z.b. Arbeitseinsatz, Arbeitskategorie.

Die Funktionierende DB hat 53 Tabellen, die Neue allerdings nur 35. 
Werden die erst bei Bedarf angelegt?
Im Log vom Server steht dann sowas hier:
`server_1               |  ERROR s.StatementExecutor$$anon$1  - SQL execution failed (Reason: (conn=7) Table 'oodev.Arbeitsangebot' doesn't exist):`
`server_1               |`
`server_1               |    select arbeitsangebot.id as i_on_arbeitsangebot, arbeitsangebot.kopie_von as kv_on_arbeitsangebot, arbeitsangebot.titel as t_on_arbeitsangebot, arbeitsangebot.bezeichnung as b_on_arbeitsangebot, arbeitsangebot.ort as o_on_arbeitsangebot, arbeitsangebot.zeit_von as zv_on_arbeitsangebot, arbeitsangebot.zeit_bis as zb_on_arbeitsangebot, arbeitsangebot.arbeitskategorien as a_on_arbeitsangebot, arbeitsangebot.anzahl_eingeschriebene as ae_on_arbeitsangebot, arbeitsangebot.anzahl_personen as ap_on_arbeitsangebot, arbeitsangebot.mehr_personen_ok as mpo_on_arbeitsangebot, arbeitsangebot.einsatz_zeit as ez_on_arbeitsangebot, arbeitsangebot.status as s_on_arbeitsangebot, arbeitsangebot.erstelldat as e1_on_arbeitsangebot, arbeitsangebot.ersteller as e2_on_arbeitsangebot, arbeitsangebot.modifidat as m1_on_arbeitsangebot, arbeitsangebot.modifikator as m2_on_arbeitsangebot from Arbeitsangebot arbeitsangebot where arbeitsangebot.zeit_bis < '2022-09-27 13:28:40.427' and arbeitsangebot.status = Offen order by arbeitsangebot.zeit_von
`

In der DB das:
`db_1                   | 2022-09-27 13:42:52 152 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 1                                                            0 to have type longblob, found type varbinary(255).`
`db_1                   | 2022-09-27 13:42:52 140 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9                                                             to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').`
`db_1                   | 2022-09-27 13:42:52 140 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 1                                                          0 to have type longblob, found type varbinary(255).`
`db_1                   | 2022-09-27 13:42:52 148 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9                                                            to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').`
`db_1                   | 2022-09-27 13:42:52 148 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 1                                                            0 to have type longblob, found type varbinary(255).`
`db_1                   | 2022-09-27 13:42:52 140 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'hist_type' at position 9                                                             to have type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB','JSON_HB'), found type enum('SINGLE_PREC_HB','DOUBLE_PREC_HB').`
`db_1                   | 2022-09-27 13:42:52 140 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 1                                                            0 to have type longblob, found type varbinary(255).
`

**Comment by AlwinEgger** [comment]
Da gibt es zwei unterschiedliche Probleme:

## OpenOlitor

Hier haben wir ein Migrationsscript, welches zu spät ausgeführt wird und ein Job beginnt bereits zu laufen :( Das ist in der neuen Major-Version des Servers gefixt (ist noch nicht produktiv).

Damit dies bei aber klappt, bitte ich dich folgendes SQL-Statement auszuführen:

```
CREATE TABLE `Arbeitsangebot` (
  `id` bigint(20) NOT NULL,
  `kopie_von` bigint(20) DEFAULT NULL,
  `titel` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bezeichnung` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ort` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `zeit_von` datetime NOT NULL,
  `zeit_bis` datetime DEFAULT NULL,
  `arbeitskategorien` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `anzahl_eingeschriebene` decimal(3,0) NOT NULL,
  `anzahl_personen` decimal(3,0) DEFAULT NULL,
  `mehr_personen_ok` varchar(1) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `einsatz_zeit` decimal(5,2) DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `erstelldat` datetime NOT NULL,
  `ersteller` bigint(20) NOT NULL,
  `modifidat` datetime NOT NULL,
  `modifikator` bigint(20) NOT NULL,
  KEY `id_index` (`id`)
);
```

## Datenbank

Die Version von MariaDB wurde in der Zwischenzeit durch dich erhöht, aber es wurde kein Upgrade gemacht. Dies kannst du tun, indem du dich auf den Container einloggst 

`docker-compose exec db /bin/sh`

und folgendes Kommando ausführst

`mysql_upgrade --user=root --password=<root_pwd>`

**Comment by budda85** [comment]
Wann genau soll ich das ausführen?
Ich habe das jetzt bei meiner neuen bestehenden "halben" Datenbank gemacht. Aber es fehlen halt noch **mehr als 15 Tabellen** in der Datenbank.
Jetzt fehlt zum Beispiel die Tabelle "ZusatzAbo".
Wenn es einfacher ist, kann ich die ganze Datenbank auch nochmal löschen und von vorne beginnen :-)

**Comment by AlwinEgger** [comment]
Die Datenbank wird eigentlich automatisch migriert. Ein Migrationsschritt schlägt im Moment fehl. Wenn du oben genanntes Query ausführst und neu startest, dann sollten die fehlenden Migrationsschritte ausgeführt werden und die fehlenden Tabellen erstellt und andere Mutationen ausgeführt.

Hast du dies ausprobiert?

**Comment by budda85** [comment]
Ja ich habe das Query für die Tabelle Arbeitsangebot ausgeführt und das mysql_upgrade in dem DB Container ausgeführt und dann auch nochmal alle Container neu gestartet. Die Tabelle Arbeitsangebot ist erstellt, aber mehr werden nicht erstellt.

Im Serverlog finde ich dann das hier:
`server_1               |  ERROR c.o.s.b.c.AktiveAbosCalculation  - Batch job failed!`
`server_1               | java.sql.SQLSyntaxErrorException: (conn=19) Table 'oodev.ZusatzAbo' doesn't exist
`

Die Tabellen habe ich jetzt:
![grafik](https://user-images.githubusercontent.com/20152200/193000005-d0c93911-67f5-45de-9a7e-25c4249c90ba.png)

**Comment by budda85** [comment]
Wie kann ich hier weiter machen?

**Comment by AlwinEgger** [comment]
Entschuldige. Ich wollte dich auf die neue OO Version hinweisen, dann hat sich der Go-Live aber etwas hinausgezögert. Denn in der neuen Version _sollte_ das Problem nicht mehr auftreten.

Hast du schon angedacht, wann du die Version updaten würdest?

**Comment by budda85** [comment]
Ne, kann ich aber machen.
Sollte ich dann noch was beachten bevor ich update? Die neue CSA erstmal wieder entfernen oder sollte das alles so gehen?

**Comment by AlwinEgger** [comment]
Wir haben https://github.com/OpenOlitor/openolitor-docker-compose auf die [Version 2.6.x](https://github.com/OpenOlitor/openolitor-server/releases/tag/2.6.12) aktualisiert. Basierst du darauf mit deiner Konfiguration und generierst du die Config-Files? Weil dann kannst du die neue CSA anfügen und musst dann die Meta-Datenstruktur erstellen (wie bisher, jetzt einfach etwas umfangreicher.) Dann kannst du den Server starten.

**Comment by budda85** [comment]
Moin,
also ich hab jetzt alles auf die neue Version gezogen. Jetzt habe ich allerdings mit der DB Probleme bzgl. des Zugriffs vom Server.
`db_1                   | 2022-10-21  6:53:43 95 [Warning] Access denied for user ''@'172.33.0.4' (using password: NO)`

Ich hab die "neue" CSA jetzt erstmal raus geschmissen und teste jetzt nur mit meiner Solawi.
Es gab ja auch ein paar Änderungen in den configs. Also auf die DB kann ich mit meinem SQL-Programm drauf zugreifen.

Ich hab jetzt folgendes gemacht.

- habe per git alle neuen Datei aus dem repo gezogen.
- Meine config auf die neue config angepasst.
- Alle Container das neue Image ziehen lassen und gestartet.

Was mir aufgefallen ist, ich hatte, warum auch immer, das latest image der MariaDB bei meinem OO am laufen.
In der neuen docker-compose ist die Version 10.7 eingetragen. Wenn ich das nutze startet mein DB Container nicht.
`db_1                   | 2022-10-21  6:17:06 0 [ERROR] InnoDB: Unsupported redo log format. The redo log was created with MariaDB 10.8.3.
db_1                   | 2022-10-21  6:17:06 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error`

Ändere ich das wieder auf latest startet wenigstens der Container, aber ich habe den Access denied fehler.

Irgendwas habe ich wohl damals falsch gemacht mit dem DB Container :(

**Comment by budda85** [comment]
Kleines Update:
Habe den Fehler gefunden. In meiner generierten server.prod.config fehlten der User und das Passwort für die Datenbank.
Jetzt läuft meine Solawi Instanz mit der -latest- Version von MariaDB wieder.
Jetzt teste ich nochmal das hinzufügen einer weiteren CSA.

**Comment by budda85** [comment]
Also so ganz rund läuft es noch nicht.
Wenn ich 2FA aktiviere, werden mir keine Mail mit dem Code zugestellt und ich bekommen nur einen `Internal Server Error` auf der Anmeldeseite.
Ich kann keine Nutzer bearbeiten oder neu anlegen. Da habe ich solche Fehler:
`19:23:36.165UTC ERROR c.o.c.domain.DefaultSystemEventStore openolitor-akka.actor.default-dispatcher-13 - Persistence failure when replaying events for persistenceId [event-store]. Last known sequence number [0]
server_1               | akka.pattern.CircuitBreakerOpenException: Circuit Breaker is open; calls are failing fast
server_1               | 19:23:38.648UTC ERROR c.o.c.mailservice.DefaultMailService openolitor-akka.actor.default-dispatcher-6 - Persistence failure when replaying events for persistenceId [mail-store]. Last known sequence number [0]
`
Das sieht für mich nach Datenbank aus, allerdings habe ich an dieser nichts geändert.
Wofür sind denn folgende neue Parameter in der json?
`mail: toAdress`
`startingPort`
`startingWebServicePort`

**Comment by budda85** [comment]
Ich denke ich gehe erstmal wieder zurück auf eine andere Version bzw. ein Backup

**Comment by AlwinEgger** [comment]
Wir hatten deine Anfrage jetzt ja per Videocall angeschaut. Ich schliesse das Ticket.

**Comment by budda85** [comment]
Ja korrekt. Danke nochmal.
