### ISSUE TITLE
Time for collaboration offers (Mitarbeit) changes on save

### ISSUE THREAD

**Issue by alexander-nbg** [OpenOlitor/OpenOlitor#114]
**Problem beschreiben / Describe the bug**

**Problem reproduzieren / To Reproduce**
1. Create a new or edit an existing collaboration item
2. Edit anything and save the change (like the start time)
3. Close the item and reopen it: **start/end times are +1h**

*Additional note:* You cannot safe the item if you only change the end date. For some reason, the "Einsatzzeit" (working time) needs to be manually adapted before saving.

**Erwartetes Verhalten / Expected behavior**
(A) Time is stored as it was set on saving the item.
(B) Information displayed after saving is identical with what is stored

**Screenshots**
Before Saving (2):
![settingBeforeSaving](https://user-images.githubusercontent.com/525857/198518717-c830c64b-683c-4b5f-9450-aa22d891a9de.png)

After saving and reloading the item (3):
![settingAfterSafingAndReloading](https://user-images.githubusercontent.com/525857/198518727-acbca610-0c79-46c8-99d1-1da3fc432beb.png)

**Browser, OS, Version**
Problem was visible by three people, I think browser/OS is not relevant. OO version is:
![ooVersion](https://user-images.githubusercontent.com/525857/198518617-4c3caadd-a3d1-4214-be5e-2a8e3beb783c.png)

**Comment by alexander-nbg** [comment]
Just a suspicion: could have something to do with summer time adjustments? I guess, something we can see after next sunday.

**Comment by mcmpp** [comment]
Hi @alexander-rd ,

this should already be fixed. Please, confirm

have a great weekend

**Comment by alexander-nbg** [comment]
Hi @mcmpp , yes UI 2.6.1 / WS 2.6.16 are now used and I was not able anymore to reproduce this issue.
Thanks!
