### ISSUE TITLE
Bericht (pdf) kann nicht erzeugt werden

### ISSUE THREAD

**Issue by PascaleGG** [OpenOlitor/OpenOlitor#115]
Berichte können mit Benutzerdefinierte Vorlagen nicht erzeugt werden. 
Mit Standardvorlage funktionniert es, aber nicht mit Benutzerdefinierte Vorlagen. Habe mit verschiedenen Vorlagen probiert:
Rechnungen / Mahnungen / Einkaufsrechnungen...
![Screenshot (30)](https://user-images.githubusercontent.com/91874955/199931058-e402c967-4e98-4752-93e8-25305dc3a215.png)
![Screenshot (31)](https://user-images.githubusercontent.com/91874955/199931061-aa076938-eb57-4ef4-b926-8b5d27f2592f.png)

**Comment by AlwinEgger** [comment]
Dieses Problem sollte nun behoben sein.

**Comment by PascaleGG** [comment]
Super!!! Funktionniert. Merci!
Liebe Grüsse

 

Pascale

Secrétariat TerreVision

 <http://www.terrevision.ch> www.terrevision.ch

 ***@***.***> ***@***.***

077 455 79 33
