### ISSUE TITLE
Sepa files do not work.

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#121]
We are currently having problems creating SEPA files. Our bank does not accept the files anymore. We get the error "Order type is not supported".

I have looked at an old and a new file and found some differences, which are probably not wanted.

Here is a screenshot.
On the left the working file, on the right the "broken" one.
Red fields: I have removed personal data.
Blue/yellow fields are the differences.

![grafik](https://user-images.githubusercontent.com/20152200/206407942-9b396357-61c8-42d2-bb76-31229495a190.png)

**Browser, OS, Version**
 - Browser [Firefox]
 - Betriebsystem / OS: [LInux, Windows]
 - Version WS 2.6.15

**Comment by mcmpp** [comment]
Hi @budda85 , 

I am quite surprise of the files that you are showing me as there is a list of parameter in the pmtInfId. That is obviously wrong an I do not know how you got them. And the BIC field disappeared?? I have created a test case in try.openolitor.ch and it is working fine for me. Can you check there if some configuration is very different in try and your environment. The important places are the bank configuration data for customers(D-Abo) and project (S-Proj).

![image](https://user-images.githubusercontent.com/13901369/206475190-81fe3120-feba-435f-8295-4f504534fd0c.png)


I cannot think of any recent change that would have broken this module so I am more going to configuration or wrong data

**Comment by budda85** [comment]
Hi @mcmpp 
what do you mean with D-Abo and S-Proj?
I has check my configuration in Administrator>Projekt and i think there is everything correct.
I noticed that in your header of the xml file pain.008.001.**02** is written. In my file there is pain.008.001.**07**
At try.openolitor.ch the filename has a 07 at the end but a 02 in the header.
Is there a config where i can change the version of the pain-file?

I have found an example from sunu with the same missing BIC.
https://github.com/OpenOlitor/openolitor-server/blob/7ec6646f7e4e7bd30a1f70352b4cb2d28b88c17c/src/test/resources/pain_008_001_07_Sunu_Beispiel.xml#L37

I have changed the locale of the Server Docker container , because I have problems with point and comma  in my invoices.
But that should have nothing to do with the creation of the pain files.

**Comment by budda85** [comment]
I just realized that this is the first time that we create a sepa file after updating to version 2.6.15

**Comment by mcmpp** [comment]
We had a session and now the sepa file seems to be the correct one. Please, close when verification done

**Comment by budda85** [comment]
Thanks again for your support.
The Sepa file is now again accepted by our bank.

If someone has the same problem and for documentation:
I had a wrong version of the UI. We have changed to the latest stable:
Admin UI: 2.6.7
Customer UI: 2.5.7
