### ISSUE TITLE
Report_Korb_Inhalt_falsch!

### ISSUE THREAD

**Issue by PascaleGG** [OpenOlitor/OpenOlitor#126]
Korbinhalt Report zeigt 10x mehr bei kg und Stück. 

![Screenshot (66)](https://user-images.githubusercontent.com/91874955/213981119-e8151130-9fec-4b7e-b8a5-6fb9b32858f4.png)

**Comment by AlwinEgger** [comment]
Könntest du uns bitte kurz sagen, um welchen Report es sich handelt?

**Comment by AlwinEgger** [comment]
Ah ja, ich habe den Repot gefunden und das `REPLACE(lpos.menge, ".00", "")` durch `ROUND(lpos.menge,1)` ersetzt. So stimmts.

**Comment by PascaleGG** [comment]
Vielen Dank! Ist wieder in Ordnung.
