### ISSUE TITLE
Hide "Liefertag" on Login

### ISSUE THREAD

**Issue by alexander-nbg** [OpenOlitor/OpenOlitor#128]
**What workflow is enhanced by this request?**
As a crop sharer, I need to know my Liefertag. However, as honorary support for maintaining the data, I also need to get efficient.

**Context:** To adjust our tours, it occasionally happens that a depot needs to shift it's delivery date. If we would get this right for all crop sharers on their login page, we would need to end all Abos (including Zusatzabos) and start new ones for the new Liefertag. This day is, however correct anyway for the decision if crop sharers get a delivery in a calender week. Contracts are on monthly basis: if the Wednesday is within the month - they get the delivery.

**Description of the solution**
We would like to be able to hide the "Liefertag" field in the top left of the login. We will, instead, write the delivery data into the depot information Öffnungszeiten (see issue #127) which is very quick to change.

**Possible Alternatives**
A quickler solution on changing the Vertriebsart to an Abo, taking over all ZusatzAbos. But I consider this much more complicated and risky while still being more effort for our honorary support.

**Comment by AlwinEgger** [comment]
Hi @alexander-rd 

I think OpenOlitor can cover your needs as is:

- The possibility to upload a custom CSS file for the Kunden-/Mitgliederportal enables you to hide elements on the frontend. The following entry in the CSS will hide it:
```
.kundenportal .liefertag {
  display: none;
}
```
- The liefertag on the Vertriebsart is only used to be displayed and to calculate future delivery-dates. You are free to make exeptions and choose another day of the week for a delivery. Just delete the future delivery date not valid and add another one on your Vertriebsart.

Does this help you?

**Comment by alexander-nbg** [comment]
Hi @AlwinEgger , yes this helped. I wasn't aware of this CSS. Are the sections/options of the CSS defined somewhere? A quick search did not help me. I think, I would also like to disable the section "Mitgliedsbeiträge".

**Comment by AlwinEgger** [comment]
No, there is no documentation. But you can actually have a look on the corresponding element you want to hide on the page (F12/right click->Inspect). We try to set a class on most sections, like the above mentioned `liefertag`. If you find one like this on the element, you may hide it or modify it's look using the same pattern.

And there is other possibilities to select almost any desired element on a page using CSS: https://www.w3schools.com/cssref/css_selectors.php

**Comment by alexander-nbg** [comment]
Yes, that was sufficient. Was not aware on how to get this info << not a web developer. ;)
All resolved! Thanks, @AlwinEgger

**Comment by AlwinEgger** [comment]
No problem. Have fun with OpenOlitor.
