### ISSUE TITLE
Mengen in Korb Report do not match Auslieferungskorbdetail und Lieferplanung

### ISSUE THREAD

**Issue by PascaleGG** [OpenOlitor/OpenOlitor#129]
**Die Mengen im Korb Report do not match Ausliefrungsliste**

Die Korbinhaltliste, die wir exportieren, für unsere Homepage und für die Abonnenten vor Ort ausdrucken, haben nicht die gleiche Zahlen/Mengen als in der Lieferlanung und Auslierfungskorbdetailliste. See screenshots:

![Screenshot (69)](https://user-images.githubusercontent.com/91874955/216272797-c1be39f5-0363-4bd4-90cc-79055ae96742.png)
![Screenshot (70)](https://user-images.githubusercontent.com/91874955/216272853-26e57193-08db-4058-a35e-28c0a3e23dba.png)
![Screenshot (71)](https://user-images.githubusercontent.com/91874955/216272894-9a9cf6c0-02e0-4f93-bfbd-7c126daf1ef8.png)

**Comment by AlwinEgger** [comment]
Zur Generierung der Korbdetails hattet ihr wohl nur das Depot Mett ausgewählt. Für die 7 Körbe dort stimmen die Zahlen ja mit den Werten der Lieferplanung überein. (Die Werte werden summiert.)

https://terrevision.openolitor.ch/admin/#/depotauslieferungen?q=id%3D130322,130323,130321&g=Alle&tf=%7B%7D

Dein dritter Screenshot kann ich nicht einordnen. Generiert ihr dieses Dokument auch aus OpenOlitor? Falls ja, über welchen Export?

**Comment by PascaleGG** [comment]
select

  ROUND(ROUND(2 * lpos.preis / 0.83, 1) / 2, 2) as Preis_Prix,

  prod.name,

  CONCAT(

    ROUND(lpos.menge, 1),

    " ",

    REPLACE(

      REPLACE(

        REPLACE(lpos.einheit, "Bund", "Bnd/bte"),

        "Stueck",

        "St/pc"

      ),

      "Kilogramm",

      "kg"

    )

  ) as menge,

  REPLACE(

    REPLACE(

      REPLACE(

        l.abotyp_beschrieb,

        "Grosser Korb",

        "Gross/Grand"

      ),

      "Kleiner Korb",

      "Klein/Petit"

    ),

    "Mini Korb",

    "Mini"

  ) as Abo,

  lpos.produkt_beschrieb as produkt

from

  Lieferposition lpos

  left join Lieferung l on lpos.lieferung_id = l.id

  left join Produzent prod on prod.id = lpos.produzent_id

where

  l.lieferplanung_id = 172

  and (

    l.abotyp_beschrieb = "Grosser Korb"

    or l.abotyp_beschrieb = "Kleiner Korb"

    or l.abotyp_beschrieb = "Mini Korb"

  )

order by

  Abo,

  lpos.produzent_kurzzeichen;

 

 

Pascale

Secrétariat TerreVision

 <http://www.terrevision.ch> www.terrevision.ch

 ***@***.***> ***@***.***

077 455 79 33

**Comment by AlwinEgger** [comment]
Ah ja, Mengen werden auf eine Stelle hinter dem Komma gerundet. 

Ersetze mal:

`ROUND(lpos.menge, 1), `=> `ROUND(lpos.menge, 2),`
