### ISSUE TITLE
Arbeitseinsätze & Abos - Soll EInsatz einfügen

### ISSUE THREAD

**Issue by PascaleGG** [OpenOlitor/OpenOlitor#138]
Arbeitseinsätze & Abos - Soll EInsatz einfügen

Wie /Wo kann ich den Soll-Einsatz für jeden Mitglied einfügen/einstellen? 
![Screenshot (6)](https://user-images.githubusercontent.com/91874955/226606757-df40974f-dea4-4faf-b03e-84b5bad8303c.png)
 
Danke.

**Comment by GHSGruber** [comment]
Hallo  PascaleGG,

das wird im Abotyp gepflegt.

**Comment by PascaleGG** [comment]
Okay, merci! LGPascale On 21 Mar 2023, at 14:17, Wolfgang Gruber ***@***.***> wrote:﻿
Hallo  PascaleGG,
das wird im Abotyp gepflegt.

**Comment by AlwinEgger** [comment]
Danke @GHSGruber , genau so ist es :)
