### ISSUE TITLE
Beta

### ISSUE THREAD

**Issue by Kaischenk** [OpenOlitor/OpenOlitor#15]
Hallo,
ich würde gerne mit unserer Solawi an der Beta mitmachen.
Könnt ihr mir die Zugangsdaten zukommen lassen auf dem https://wwwtest.openolitor.ch/#/login war ich bereits und habe mir die funktionalität angesehen.

>Kai

**Comment by ghost** [comment]
Auch ich würde gerne mit unserer ganz frischen Solawi an der Beta teilnehmen und bitte um weitere infos/zugangsdaten.

LG,
Alex

**Comment by ClSchreiber** [comment]
Lieber Alex
Wir nehmen gerne per Mail mit Dir Kontakt auf, wie wir das schon bei Kai gemacht haben.
Herzlicher Gruss
Claudia Schreiber
Verein OpenOlitor

**Comment by ClSchreiber** [comment]
Lieber Alex
Bitte sende uns ein Email an info@openolitor.ch, damit wir bald mit Dir Kontakt aufnehmen können.
Herzlicher Gruss
Verein OpenOlitor
Claudia Schreiber
