### ISSUE TITLE
Login unter try.openolitor.ch funktioniert nicht

### ISSUE THREAD

**Issue by Cruiser79** [OpenOlitor/OpenOlitor#151]
Egal ob ich mich mit dem konsumenten oder admin Login anmelde, ich bekomme jedes mal die Fehlermeldung

`<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.24.0</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

**Comment by mcmpp** [comment]
Hi @Cruiser79 , 

I apologize for any inconvenience. This issue commonly arises when there is a disconnection between the frontend and backend. In the testing environment, occasional occurrences may result from excessive usage, given its open nature. However, it's important to note that this stability issue is not prevalent in the production environment. In production, resources are more abundant, tailored to demand, and additional measures are in place to mitigate the impact of any disruptive activities from neighboring entities.
