### ISSUE TITLE
Zahlungsdetails in json-Extract für Rechnung fehlen

### ISSUE THREAD

**Issue by GHSGruber** [OpenOlitor/OpenOlitor#157]
**Problem beschreiben / Describe the bug**
Die json-Datei für die Vorlage zum Rechnungsdokument enthält keine Informationen zu den Zahlungsdetails. Zumindest einige dieser Details müssen auf der Rechnung mit ausgedruckt werden, wenn es sich um Zahlung per Lastschrift handelt. Es sollten daher alle Felder aus den Kontodaten des Kunden in die json-Datei mit aufgenommen werden. Vor allem natürlich auch die neueren Felder für Mandats-Id und Unterschriftsdatum(date_of _signature).

The json file for the invoice document template does not contain any information on the payment details. At least some of these details must be printed on the invoice if it is a direct debit payment. All fields from the customer's account details should therefore be included in the json file. Above all, of course, the newer fields for mandate ID and signature date (date_of _signature).
**Problem reproduzieren / To Reproduce**
Wie kann das Problem reproduziert werden?

**Erwartetes Verhalten / Expected behavior**
Wie wäre das erwartete Verhalten? 

**Screenshots**
Screenshots helfen mehr als 1000 Worte :)

**Browser, OS, Version**
 - Browser [e.g. Chrome, Firefox]
 - Betriebsystem / OS: [e.g. LInux, Windows]
 - Version [e.g. 56]

**Comment by mcmpp** [comment]
done

**Comment by GHSGruber** [comment]
works fine - thank you
