### ISSUE TITLE
Rechnungsdatum wird als TimeStamp statt als Datum dargestellt

### ISSUE THREAD

**Issue by GHSGruber** [OpenOlitor/OpenOlitor#158]
**Problem beschreiben / Describe the bug**
Das Rechnungsdatum wird in der Anzeige der Rechnung im Timestamp-Format (incl. Uhrzeit) angezeigt. Eine Anzeige als Datum ist passender.

The invoice date is shown in the invoice display in timestamp format (incl. time). A display as a date is more suitable.

**Problem reproduzieren / To Reproduce**
siehe Screenshot

**Erwartetes Verhalten / Expected behavior**
Wie wäre das erwartete Verhalten? 

**Screenshots**
![image](https://github.com/OpenOlitor/OpenOlitor/assets/15242843/40d77741-55f0-48fb-83ad-d00dc0ab5877)

**Browser, OS, Version**
 - Browser [e.g. Chorme
 - Betriebsystem / OS: Windows 11
 - Instanz: try.openolitor.ch
 - Version ![image](https://github.com/OpenOlitor/OpenOlitor/assets/15242843/be316b12-0317-484b-92f7-48565360de39)

**Comment by mcmpp** [comment]
done!

**Comment by GHSGruber** [comment]
works fine - thank you
