### ISSUE TITLE
Sunu demo site passwd not set

### ISSUE THREAD

**Issue by y0va** [OpenOlitor/OpenOlitor#16]
Hi guys,
The standard credentials seem to be unset on https://sunuwwwtest.applicationcloud.io

![image](https://user-images.githubusercontent.com/21321805/41029772-e0691d14-697c-11e8-96ca-87a6ce814d6f.png)

**Comment by mcmpp** [comment]
Hi y0va,

thank you for letting us know! The credentials are reestablished again.
