### ISSUE TITLE
New column member-description for invoice-overview

### ISSUE THREAD

**Issue by GHSGruber** [OpenOlitor/OpenOlitor#162]
**In welchem Geschäftsfall/Ablauf hilft diese Erweiterung? / What workflow is enhanced by this request? **
Bearbeitung und Auswertung von Rechnungen / Processing and evaluation of invoices

**Beschrieb der Lösung / Description of the solution**
Einfügen einer neuen Spalte zwischen Kunde/Mitglied und Titel mit der Kunden-/Mitgliedsbezeichnung. 
Insert a new column between customer/member and title with the customer/member name. 

**Mögliche Alternativen / Possible Alternatives**
Gibt es Alternativen zur beschriebenen Lösung? Sind diese gleichwertig? Warum nicht?

Is there alternatives to this solution? Are they equally valid? If not, why?

**Comment by mcmpp** [comment]
Hi @GHSGruber , 

Just for my understanding, you suggest to add the column "designation" here:

![image](https://github.com/OpenOlitor/OpenOlitor/assets/13901369/75c46a25-2c20-415e-a937-82a37b1e12f6)

Am I right?

**Comment by mcmpp** [comment]
done!
