### ISSUE TITLE
New colums in invoice detail overview

### ISSUE THREAD

**Issue by GHSGruber** [OpenOlitor/OpenOlitor#163]
**In welchem Geschäftsfall/Ablauf hilft diese Erweiterung? / What workflow is enhanced by this request? **
Bearbeitung und Auswertung von Rechnungspositionen / Processing and evaluation of invoices detail lines

**Beschrieb der Lösung / Description of the solution**
Einfügen folgender zusätzlicher Spalten in der Rechnungspositonsübersicht (ähnlich der Übersicht der Abos):
a) Beschreibungstext des Abotyps (selektierbar)
b) Kundennummer und Kundenbezeichnung 

Insert the following additional columns in the invoice item overview (similar to the overview of subscriptions):
a) Description text of the subscription type (selectable)
b) Customer number and customer name 

**Mögliche Alternativen / Possible Alternatives**
Gibt es Alternativen zur beschriebenen Lösung? Sind diese gleichwertig? Warum nicht?

Is there alternatives to this solution? Are they equally valid? If not, why?

**Comment by mcmpp** [comment]
done!
