### ISSUE TITLE
Number of characters in EMail-Forms is limited zu 30 characters

### ISSUE THREAD

**Issue by GHSGruber** [OpenOlitor/OpenOlitor#164]
**In welchem Geschäftsfall/Ablauf hilft diese Erweiterung? / What workflow is enhanced by this request? **
Benutzen der E-Mail-Forms

**Beschrieb der Lösung / Description of the solution**
Die Anzahl der Zeichen für das Subject im E-Mail-Form und in der E-Mail-Vorlage ist auf 30 Zeichen begrenzt. Kann dieses Limit erhöht werden ( z. Bsp. 100 Zeichen)

The number of characters for the subject in the e-mail form and in the e-mail template is limited to 30 characters. Can this limit be increased (e.g. 100 characters)?

**Mögliche Alternativen / Possible Alternatives**
Gibt es Alternativen zur beschriebenen Lösung? Sind diese gleichwertig? Warum nicht?

Is there alternatives to this solution? Are they equally valid? If not, why?

**Comment by mcmpp** [comment]
done!
