### ISSUE TITLE
Wrong entry in SEPA-XML-export

### ISSUE THREAD

**Issue by joseph-LG** [OpenOlitor/OpenOlitor#166]
**Problem beschreiben / Describe the bug**
1.  SEPA-XML contains in <ReqdColltnDt> not the date from "Fälligkeitsdatum" (see also here: https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/xml-sepa-zeilen-inhaltlicher-aufbau/), but the same date when the SEPA is created.
2. The banking software doesn't accept SEPA debits which aren't in the future

1. Die SEPA-XML-Dateien enthalten in <ReqdColltnDt> nicht das gewählte Fälligkeitsdatum, sondern den aktuellen Tag.
2. Die Banksoftware akzeptiert keine Lastschriften, die nicht in der Zukunft liegen.

**Problem reproduzieren / To Reproduce**
create "Rechnung"
create sepa-xml "pain_008_001_07" resp. "pain_008_001_02"

**Browser, OS, Version**
 - Browser  Firefox]
 - Betriebsystem / OS: [e.g. LInux,
Version:
UI v2.6.35 | #20240807
WS 2.6.40 | #20240806
ENV prod

**Comment by mcmpp** [comment]
@joseph-LG , nice to see you around. Is this still an issue?

**Comment by joseph-LG** [comment]
no, it's solved.
sometimes it's creates files with the name 02 at the end, sometimes with 07
but it has no effects to it's functionality
