### ISSUE TITLE
[sunu] English translation

### ISSUE THREAD

**Issue by y0va** [OpenOlitor/OpenOlitor#18]
Englisch wird in dem Auswahlmenü als Option angezeigt, dessen Auswahl hat aber keine Auswirkung auf die Darstellung des Interfaces. 
Wie ist der Status der Übersetzung ins Englische?

**Comment by AlwinEgger** [comment]
@mcmpp has translated most of it

Die Übersetzung ist fast komplett, allerdings ist vieles noch nicht zurück in die Applikation eingeflossen (weil bisher keine Anforderung).

Der Status ist hier ersichtlich (und es kann auch gerne mit übersetzt werden):
http://translate.openolitor.org/project/openolitor/en#

**Comment by y0va** [comment]
Schade dass noch so wenig zurück in die Applikation geflossen ist. Würde sunu gerne im europäischen Kontext präsentieren. Dazu wäre eine englischsprachige Oberfläche recht praktisch...

**Comment by AlwinEgger** [comment]
Na dann haben wir jetzt ja den Anwendungsfall.
Wann würdest du die Demo gerne machen?

Wer Zeit und Lust hat kann gerne auch die automatische Übernahme der Übersetzungen aus Crowdin in den Build-Prozess umsetzen.

**Comment by y0va** [comment]
Naja, die Präsi ist eigentlich schon fertig, halt jetzt erstmal auf deutsch kann die Screenshots aber vielleicht nochmal neu machen, wenn die Sprachdaten da sind. Allerdings ist ie erste Show schon nächste Woche Donnerstag...

Meine Zeit ist leider auch  begrenzt :-/
