### ISSUE TITLE
Neues Produkt erstellen erzeugt Fehler

### ISSUE THREAD

**Issue by SigCon** [OpenOlitor/OpenOlitor#3]
![openolitor-neues-produkt](https://cloud.githubusercontent.com/assets/10470682/13796205/b25f0a8e-eb05-11e5-8e47-72619cd847de.jpg)
Wenn ein neues Produkt erstellt wird, erscheint folgender Fehler:
[$resource:badcfg] Error in resource configuration for action `get`. Expected response to contain an object but got an array (Request: GET http://test.openolitor.ch/m1/kunden) http://errors.angularjs.org/1.4.9/$resource/badcfg?p0=get&p1=object&p2=array&p3=GET&p4=http%3A%2F%2Ftest.openolitor.ch%2Fm1%2Fkunden

**Comment by AlwinEgger** [comment]
Vielen Dank für die Rückmeldung.
In welchem Browser ist der Fehler aufgetreten?

**Comment by SigCon** [comment]
Das war Firefox 44.0.2 auf Mac OS X 10.11.3 // Safari Version 9.0.3 (11601.4.4) geht // Chrome Version 48.0.2564.116 (64-bit) geht. Jetzt geht aber auch Firefox 44.0.2. Wurde was geändert? Falls nicht, kann z.B. die exakte Reihenfolge oder die Kombination der Felder (Value, leer, ausgefüllt) evtl. noch eine Rolle spielen.

**Comment by AlwinEgger** [comment]
Der Server ist am 15.03.2016 um 23:24:58 aufgrund von zu wenig Speicher gecrasht und hat sich neu gestartet.
Ich gehe davon aus, dass dies mit dem Zeitpunkt deines Tests zusammen viel.
Wir sind daran den Ressourcenbedarf der Applikation zu optimieren. Vorerst stelle ich dem Server aber etwas mehr Speicher zur Verfügung:
[OpenOlitor/openolitor-server/commit/480f8f39f1d9506ff797aea0e33155b0ad98aec7](https://github.com/OpenOlitor/openolitor-server/commit/480f8f39f1d9506ff797aea0e33155b0ad98aec7)
