### ISSUE TITLE
Your web page blocks my web browser

### ISSUE THREAD

**Issue by aldobelus0** [OpenOlitor/OpenOlitor#32]
Hello.
I'm interested in share your project with other people who, like myself, are focus in build a better environment, in change it. I discover you at the FOSDEM2020 talk. When I tried to share your web page, the home address blocks my web browser! Not the other pages of your site, only that one. I suspect the trial demo can have something to do, at seeing my system monitor. You should test it, I guess.

It happens at Brave, the web browser based on Chromium code, the same one as Chrome. It has some differences, but the base is that one. 

If you could do something, I would be thankful.

I will stop share your project untill I see this page have a better behaviour. I don't want to send people and let them astonished with such issues. 

Thanks for your effort and best wishes. Greetings.

**Comment by mcmpp** [comment]
Hi @aldobelus0 ,
I am glad you are interested in OpenOlitor. Let's try to solve your problem. As you mention, the home page is blocking your Brave browser. Are you trying to access this page, right?? https://openolitor.org/ 

The demo is hosted here : https://wwwtest.openolitor.ch/#/login . Could you please also test if this one is working for you??

Have a good Saturday and please, let me know that we can solve this issue

**Comment by aldobelus0** [comment]
> Are you trying to access this page, right?? https://openolitor.org/

That's right. I try and success. I enter and, then, after a few seconds (3, 4?), my browser is blocked.

---

> https://wwwtest.openolitor.ch/#/login . Could you please also test if this one is working for you??

It worked. But, again, my browser is blocked if I enter again at your home page. And, being thorough, **the home address for OpenOlitor at my browser is that one:**

https://openolitor.org/pagina-principal/

Could, maybe, be this spanish address the origin of the issue? I don't know, really, only giving info... By the way, I'm in Spain, don't be wrong!

**Comment by mcmpp** [comment]
hi @aldobelus0 , 

I was making some testing about your issue. Here the outcome: 
- the website is build with wordpress and kahuna style. I made sure every plugin and component is updated.
- I have installed brave in my computer and open the website. I had no issues opening it in any of the available languages. The version that I currently have: 
_Version 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)_
my system is Ubuntu 18.04.4 LTS
- I tried with chromium and again successful. The version is : 
_Version 79.0.3945.130 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)_
- if I change the default language of the browser it goes to https://openolitor.org/pagina-principal/ as expected and successfully load the page without any block.

Could it be related to plugins or some customization you have in your browser??

**Comment by aldobelus0** [comment]
> Could it be related to plugins or some customization you have in your browser??

I can't figure out how could this happen, because I tried too with other browser, Qupzilla, and had the same problem. Though, I did it with Firefox and  worked like a charm. 

I don't know what to tell you. Two browsers bad, one good. What you say about plugins or customization seems rare, at the light of this experiences, this different attempts.

I can't tell you more. If you don't see problem at your side of the page, your customization or the web page design, I don't know. Thanks for your attention.

**Comment by mcmpp** [comment]
I installed the new version of Qupzilla, Falkon, and it works too. Could you please open the console of the browser and see if there are calls that are not answered or any kind of error you might see??
What's the version of the browser engine?? we can setup a time to debug this issue...

**Comment by mcmpp** [comment]
![image](https://user-images.githubusercontent.com/13901369/74267351-31de0d80-4d06-11ea-9371-dd657f4a79e2.png)

all the calls are successful

![image](https://user-images.githubusercontent.com/13901369/74267492-6f429b00-4d06-11ea-8a63-72f4f7d31d03.png)

the official version in arch linux

**Comment by aldobelus0** [comment]
Qupzilla is moving better your page today, but doesn't end loading, ever. Despite that, is visible a warning message:

![QUPZILLA-OLITOR](https://user-images.githubusercontent.com/15985449/74373859-915b1c80-4ddd-11ea-85e9-a7c0a176574a.png)

This is the capture of Brave, which is still blocked when I load the home page.

![QUPZILLA-OLITOR_1](https://user-images.githubusercontent.com/15985449/74374699-3296a280-4ddf-11ea-9410-85da5e5f2284.png)
![QUPZILLA-OLITOR_0](https://user-images.githubusercontent.com/15985449/74374708-375b5680-4ddf-11ea-9b8c-a676e42e14fb.png)

**Comment by aldobelus0** [comment]
Sorry, I forgot to offer you the browser versions and stuff. 

**My OS** is Trisquel, an Ubuntu _FSF_ endorsed. [Version Trisquel: 8.0 (Flidas) (April 2018). Based on Ubuntu 16.04 (Xenial Xerus). Soported untill 2021](https://trisquel.info/en/wiki/flidas).

---

This is the **Brave** one:

Versión 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

![QUPZILLA-OLITOR_2](https://user-images.githubusercontent.com/15985449/74588395-74506480-4ffc-11ea-8166-5360072945f9.png)

---

**_Qupzilla/Falkon**_: Versión 1.8.9 // Versión _WebKit_: 538.1
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/538.1 (KHTML, like Gecko) QupZilla/1.8.9 Safari/538.1

![QUPZILLA-OLITOR-1](https://user-images.githubusercontent.com/15985449/74588366-3fdca880-4ffc-11ea-901a-dd6c9cb622c3.png)

---
**Customization** 

ImTranslator

![QUPZILLA-OLITOR_4](https://user-images.githubusercontent.com/15985449/74588492-56373400-4ffd-11ea-9156-d177cee5d1ad.png)

---

![QUPZILLA-OLITOR_3](https://user-images.githubusercontent.com/15985449/74588467-0f493e80-4ffd-11ea-9bf1-0923a34cd707.png)

I don't know if you need anything else.

**Comment by mcmpp** [comment]
Hi @aldobelus0 ,

I have installed Trisquel 8.0 in spanish on a virtualbox, installed the brave browser and still I can go into the page with no problem and display all the information.
I think this confirms that your particular installation is the one creating and issue that, to be honest, I cannot imagine what it can be... 

![image](https://user-images.githubusercontent.com/13901369/75055392-34deb800-54d5-11ea-9b9d-b4d4e6c00871.png)

I am afraid I cannot help you further... I could not really duplicate your issue in any browser...

**Comment by mcmpp** [comment]
no high consumption of resources . The machine that I created was rather small.

![image](https://user-images.githubusercontent.com/13901369/75055633-afa7d300-54d5-11ea-9bde-4d97e518cefd.png)

**Comment by aldobelus0** [comment]
Didn't you saw anything unusual here?


> Qupzilla is moving better your page today, but doesn't end loading, ever. Despite that, is visible a warning message:
> 
> ![QUPZILLA-OLITOR](https://user-images.githubusercontent.com/15985449/74373859-915b1c80-4ddd-11ea-85e9-a7c0a176574a.png)
> 
> This is the capture of Brave, which is still blocked when I load the home page.
> 
> ![QUPZILLA-OLITOR_1](https://user-images.githubusercontent.com/15985449/74374699-3296a280-4ddf-11ea-9410-85da5e5f2284.png)
> ![QUPZILLA-OLITOR_0](https://user-images.githubusercontent.com/15985449/74374708-375b5680-4ddf-11ea-9b8c-a676e42e14fb.png)

You asked for it!

> I installed the new version of Qupzilla, Falkon, and it works too. **Could you please open the console of the browser and see if there are calls that are not answered or any kind of error you might see??**
> What's the version of the browser engine?? we can setup a time to debug this issue...

As I showed you previously at the comments, this is the Brave version:

> This is the Brave one:
> 
> Versión 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)

**Comment by mcmpp** [comment]
Hi there, 

the console looks fine. There are no errors and all calls where successfully resolved. As I have suggested previously, the only plausible explanation is that there is some issue with your local setup. 

In any case, as you wanted to share the project and you have still issues opening it, here some links and info that could be helpful: 
- a demo instance https://wwwtest.openolitor.ch
- the fosdem 2020 talk + summary of the project:  https://fosdem.org/2020/schedule/event/openolitor_community_supported_agriculture/

If you want some more information in Spanish, you can contact me directly.

**Comment by aldobelus0** [comment]
Still doing it... I don't know. I will share your project, you'll see if I'm the only one with problems loading your page. Thank you for your support and good luck.
Greetings!

**Comment by mcmpp** [comment]
ok, thanks !!
