### ISSUE TITLE
documentation mixed up?

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#33]
Hey, 
i found this nice project. 
Is it possible that the documentation from 

> Doku Technisch_Client_Cloud Setup

and 

> Doku Technisch_Server_Cloud Setup

is mixed up?

**Comment by mcmpp** [comment]
Hi @budda85 

I am glad you are interested in OO. Thanks for the message and for finding this error!
I have interchange them so now they are in the right order.

have a good day

**Comment by budda85** [comment]
Hey @mcmpp 
thx for your answer. I have one more question if that's not a problem :-)
what is the "openolitor-client-core" exactly doing?
I wan't to run OO without a CF and test it with debian. If that works, I would like to join your club and if desired, I could also write a manual for that.
What is the main language at OO github? English or german? :-)
Please keep going with this fantastic project.

THX

**Comment by mcmpp** [comment]
Hi @budda85 

openolitor-client-core was originally a project with shared components for the admin portal and the customer portal. With the time, those 2 portals are not sharing any component anymore so the client-core project is only used by the admin portal. At this point, this project could be merged to the admin portal but we never took the time to do it.
The main language in the team is german but you are talking to the non german speaker :)
If you need any support in german, just go ahead and someone could take the relay !

Have a good day

**Comment by budda85** [comment]
Hi @mcmpp 
thanks for your answer. I try it in english ;-)
Over the Weekend i compile the Server for testing, configure the config with my SQL data, prepare the database with the scheme and start it.
So the Database was filled and the server is running.
Then i compile the admin portal and start it on my machine. I can login and test everything.
during the test, i did not miss anything that the core module would provide to me. My test data was inserted into the database and saved. 
What should I miss?
And one more question: is it possible to deactivate the Amazon S3 Service? Is it only for i.e. to save a bill?
greets and have a nice week.

**Comment by mcmpp** [comment]
Hi @budda85 , 

I didn't mention in my previous email. The core project is loaded automatically by the admin portal so you do not need to worry much about it. So, it seams you made it! 
The s3 service is a storage service that we use to store all files needed by OO. There are many providers, docker images, etc. you should set it up independently and link it through credentials. In the server project, at openolitor-server/docker/fakes3 you can run a fake s3 server locally that you can try it with full functionallity.
  
```
docker build .
./run.sh [the id you got from the previous command]
```
if you run without s3 some functionalities will not work...

Please, if you find any suggestion, do not hesitate to come back to us!

Have a good day

**Comment by budda85** [comment]
Hey @mcmpp 
ah, then i've misunderstod the client_core. 
Now I have it working on an debian machine, with MySQL, Apache and MinIO (S3).
Is there any documentation wich funktions are using the S3 storage?
Now i'm testing the full function and go through your checklist in the wiki.
During the compilation process of the clients there are some vulnerabilities. Is this a problem with the security? Unfortunately I do not know java properly and cannot support that, I would have to learn it first.

Should i contribute with an documentation for an debian system or is this not desired?
Greetings an thx for your support.

**Comment by mcmpp** [comment]
Hi @budda85 

That is great!! the S3 is for example being used in the invoice creation. When you create an invoice, you can select the option that you want  to store the file. That way, you do not need to generate it again. See the screenshot from the test instance: 
![image](https://user-images.githubusercontent.com/13901369/80812487-5ee4e280-8bc8-11ea-9b72-83007a984a6c.png)

Do you have the vulnerabilities?? If there is a possibility to share those I would appreciate it 
I do not know if you have seen that there are some videos explaining some of the functionalities. That might be helpful for you:
https://openolitor.org/arbeitsschritte-und-prozessabfolgen/
In any case I am open to answer to your questions about features and functionalities

About the documentation, that could be great if you could document the process of deployment in a debian server.

Thanks a lot!

**Comment by budda85** [comment]
Hi @mcmpp 
okay i see the invoice in my storage when i use the "PDF ablegen" option. So i think that is working :-)
But when i wan't to upload an logo, there is this error:
![upload icon](https://user-images.githubusercontent.com/20152200/81003147-ae3a4580-8e4a-11ea-9d03-aebdec55b5fd.png)
Have you an idea?
Vulnerabilities were shown to me after running `npm install `on the client.
![vulnerabilities](https://user-images.githubusercontent.com/20152200/81003419-26a10680-8e4b-11ea-8c17-4717aad29baf.png)
After `npm audit fix` i see less vulnerabilities
![vulnerabilities after npm audit fix](https://user-images.githubusercontent.com/20152200/81003548-5819d200-8e4b-11ea-9da8-d329cf30d9f1.png)
and bower show to me as deprecated
![bower deprecated](https://user-images.githubusercontent.com/20152200/81003639-767fcd80-8e4b-11ea-95ac-463f2801c65c.png)
But don't get me wrong, I don't know anything about it yet. It is the first time, that i use npm and bower. Maybe it's not a problem :-)

I noticed something else in the application.conf. I think the section `# DB Seed configuration` and `# Security configuration` are double in it, isn't it?

And one more question :-)
How can i enable the `Two-Factor-Authentisierung`? I've set both option for the admins and the members to yes but there is no second Factor that i must enter. What am i doing wrong?

Thanks for the videos, i haven't seen them yet.
And again, a big thank to you, for answering all my questions.

**Comment by budda85** [comment]
Hey @mcmpp 
where should i add the documentation?

**Comment by budda85** [comment]
I've found the error with the Logo-upload. It is a problem with the german special characters like ä ü ö :-)

**Comment by mcmpp** [comment]
Hi @budda85 ,

sorry, I was not answering for a while. I hope you resolved some of the questions with @AlwinEgger . Great that you found the error!!! Please, do not hesitate to make pull requests if you think there are improvements! About the documentation, you can clone the wiki, add the changes and make a proposal. If it is easier for you, you can send it to my email address (published on my profile) and I can publish it. If some translations are required, I can make them.

**Comment by budda85** [comment]
Since you now have a docker version available, I wouldn't do the setup guide for Debian anymore. I will see that I will write the manual for the docker image under debian.
