### ISSUE TITLE
Platzhalter in Vorlagen

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#35]
Hallo,
gibt es irgendwo eine Liste, welche möglichen Platzhalter es gibt?
Also wie in den Vorlagen z. B. {{ projekt.bezeichnung }} und {{produzent.name}}

Danke und Gruß
Jan

**Comment by AlwinEgger** [comment]
Hallo Jan

Jeder Report bietet unterschiedliche Daten an, welche abgefüllt werden können. Diese sind sehr umfangreich und ändern bei Ergänzungen auch mal (es werden mehr, gestrichen wird nicht).

Am Einfachsten kannst du die Datenstruktur sehen, indem du beim gewünschten Bericht in der Liste der Vorlage ganz unten Datenextrakt anwählst. Nun wirst du als Rückmeldung die strukturierten JSON-Daten erhalten, welche die Grundlage zur Generierung ebendieses Berichts ist.
![image](https://user-images.githubusercontent.com/4997364/82761798-6ed59800-9dfd-11ea-8fff-97a857be4ccb.png)

Mit diesen Daten kannst du nun deine JSONPath-Expression validieren, bspw. hier: [JSONPath Validator](https://jsonpath.com)

Weitere Details zu den Möglichkeiten der Report-Vorlagen [findest du auf unserer Webseite](https://openolitor.org/category/anleitungen/)

Ich hoffe, die Info hilft dir weiter!

**Comment by budda85** [comment]
Hallo Alwin,
danke für die schnelle Rückmeldung.
Ich finde den Menüpunkt aus deinem Bild nicht. Wo kann ich diesen finden?

**Comment by AlwinEgger** [comment]
Du findest den Menüpunkt im jeweiligen Wizard zur Erstellung von Dokumenten:

![image](https://user-images.githubusercontent.com/4997364/82784746-74fd6000-9e61-11ea-8d78-27775f5ace63.png)

![image](https://user-images.githubusercontent.com/4997364/82784696-5dbe7280-9e61-11ea-8914-78c265194095.png)

**Comment by budda85** [comment]
Ahh perfekt, Danke!
Damit komme ich erstmal weiter.
