### ISSUE TITLE
Zwei Faktor Authentifizierung aktivieren

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#36]
Was muss ich genau machen um die Zwei Faktor Authentifizierung zu aktiveren?
Ich habe es in der Admin-Oberfläche aktiviert. Muss ich es auch noch extra in der application.conf aktivieren?

Ich weiß, ich nerve bestimmt mit meinen ganzen Fragen :-)

Danke und Gruß
Jan

**Comment by AlwinEgger** [comment]
Ja, um die Second-Factor Authentifizierung grundsätzlich zu aktivieren, muss erst noch in der application.conf der Parameter `true` gesetzt werden:

https://github.com/OpenOlitor/openolitor-server/blob/prod/src/main/resources/application.conf#L421

Bez. der Fragen: Kein Problem. Die Antwortzeit ist halt nicht immer die selbe.

**Comment by budda85** [comment]
Klappt, danke.
