### ISSUE TITLE
Backup und Restore

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#37]
Hallo,
ich teste gerade eure OO-Docker Version.
Was wäre die beste und einfachste Möglichkeit, Daten vom "alten" OO, in die OO-Docker Version zu bekommen?
Datenbank kopieren?
Danke und Gruß
Jan

**Comment by AlwinEgger** [comment]
Am einfachsten ist es ein mysqldump zu machen und im Anschluss ein Restore auf die neue Umgebung. Das sieht ca. so aus:

```
mysqldump --skip-add-locks --skip-lock-tables --no-autocommit --protocol=TCP -P 3306 --user="userBisher" --password="passwortBisher" --host=db-host "datenbank-name" > db_dump.sql

mysql --user="root" --password="[db.databaseRootPassword]" --protocol=TCP --port=3306 --host="localhost" "[csas[0].db.databaseName]"  < db_dump.sql
```

Alle Werte in [Klammern] entsprechen den Keys im [{env}.json](https://github.com/OpenOlitor/openolitor-docker-compose/blob/master/dev.json) im [openolitor-docker-compose](https://github.com/OpenOlitor/openolitor-docker-compose) Projekt.

**Comment by budda85** [comment]
Ah perfekt, hat geklappt. Danke.
