### ISSUE TITLE
Excel Export der Kundendaten kann mit Excel 14.4.7 für MAC nicht geöffnet werden

### ISSUE THREAD

**Issue by SigCon** [OpenOlitor/OpenOlitor#4]
Ein Export der Kundendaten (http://wwwtest.openolitor.ch/#/kunden) erstellt die Datei Kunden.xlsx. Diese kann mit Excel for Mac 2011 (Version 14.4.7 (141117)) nicht geöffnet werden. Ein simpler Export von Kundendaten sollte in einem möglichst einfachen Format (CSV ?) gemacht werden oder aber so, dass auch ältere Versionen von Excel die Datei öffnen können. Es braucht keine "fancy" features von Excel für eine "simple" Liste.

**Comment by SigCon** [comment]
![excel-export](https://cloud.githubusercontent.com/assets/10470682/13856528/e3cd6d2e-ec75-11e5-9f49-11f112f2f0d8.jpg)

**Comment by SigCon** [comment]
Es spielt keine Rolle, wo im Programm man einen Export macht. z.B. auch bei den Produzenten kann das Excel file nicht gelesen werden.

**Comment by AlwinEgger** [comment]
Wir haben vorerst den Standart-Export von ng-table integriert. Hier können wir noch Anpassungen vornehmen. Ich stimme dir zu, dass ein möglichst breit integrierbares Format am Besten ist: CSV.
Wir werden den Export noch anpassen und dich dann informieren.

**Comment by AlwinEgger** [comment]
Entscheid: Wir werden den Export auf dem Backend abbilden. Die Listen werden über die Webservice-Schnittstelle ebenfalls als OpenDocument Spreadsheet zur Verfügung stehen und das UI wird diese demnach dort abholen.

**Comment by AlwinEgger** [comment]
Der Export wird nun auf dem Server direkt als OpenDocument Spreadsheet erstellt. Wird mit der nächsten Installation auf Test verfügbar sein.

Siehe:
https://github.com/OpenOlitor/openolitor-server/pull/147
https://github.com/OpenOlitor/openolitor-client-core/pull/8
https://github.com/OpenOlitor/openolitor-client-admin/pull/130
