### ISSUE TITLE
export of PAIN files should be standard conform

### ISSUE THREAD

**Issue by seebi** [OpenOlitor/OpenOlitor#45]
I our current problem the PmtInfId field is longer than 35 chars which results in non-importable files.

https://www.hettwer-beratung.de/sepa-spezialwissen/sepa-technische-anforderungen/pain-format-sepa-pain-001-sct/

However, there should be tests for all limits (such as Nm <= 70, AdrLine <= 70).

Please make sure, its as conform as possible,

**Comment by mcmpp** [comment]
Hi @seebi ,

I have made some changes and opened a pull request https://github.com/OpenOlitor/openolitor-server/pull/568

**Comment by mcmpp** [comment]
@seebi , this was already merged. It will be deployed on the next version
