### ISSUE TITLE
Download of SEPA export for many invoices should skip invoices where the user has no DirectDebit payment info

### ISSUE THREAD

**Issue by seebi** [OpenOlitor/OpenOlitor#46]
Currently, I need to look for persons which do not have this info and manually de-select them.

This is manual work and extreme error-prone so my request is to skip the export automatically.

**Comment by mcmpp** [comment]
Hi @seebi ,

I was having a look on this question and if I understand it well, there is a way to do so already in place. You can use the filters for the table, even multiple of them at the same time. I made a little video with an example 

![directDebit](https://user-images.githubusercontent.com/13901369/104817585-7cbfa980-5822-11eb-9967-2b9c24ad7bca.gif)

Is this useful??

**Comment by seebi** [comment]
I agree, this is exactly what I wanted. Thx
