### ISSUE TITLE
Add mandate Id and date of signature to the payment options

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#47]
In OpenOlitor we don't have the date of the signature of the agreement of the mandate. I propose to add 2 additional fields in the payment data, which are mandatory, if the payment method is "directdebit":
(1) date of signature of the SEPA-Mandat 
(2) SEPA-Mandats-ID of the SEPA-Mandat.

**Comment by AlwinEgger** [comment]
On what model are these two fields going to be located?
=> Just saw your PRs :)
