### ISSUE TITLE
Kunden ohne eMail-Adresse

### ISSUE THREAD

**Issue by M3tr0id** [OpenOlitor/OpenOlitor#5]
Es gibt abonenten, die (auch heute noch) keine eMail haben (Leute bewusst ohne PC, "ältere Semester", etc.) - ist aber ein Pflichtfeld.

Könnte man da nicht ein Flag hinmachen, dass das Pflichtfeld entwertet bzw. mit dem man das Pflichtfeld beim Erstellen neuer Kunden fakultativ machen kann?

**Comment by rickyweb** [comment]
Bei uns haben wir bisher nur einen solchen Fall. Bei Admidio, welches wir aktuell verwenden, ist die E-Mail Adresse auch pflicht. Deshalb haben wir eine Alias-E-Mail Adresse für diesen User erstellt, welche die Mitteilungen an eine Person weiterleitet, die ihn dann anruft oder per Post informiert. Ich sehe also kein Bedürfnis für eine solche Ergänzung.

**Comment by AlwinEgger** [comment]
Die E-Mail fakultativ zu machen ist an sich kein Problem.
Es kommt halt drauf an, wie die Initiative kommuniziert. Wenn davon ausgegangen wird, dass mit einem Mail dann alle informiert sind, das Vorgehen von @rickyweb vielleicht besser. So wird gewährleistet, dass niemand vergessen geht.
Wir könnten hier aber eine Projekt-Konfigurations-Flag vorsehen, so dass die Initiative entscheidet ob E-Mails sein müssen oder nicht.

**Comment by ideadapt** [comment]
Der Vollständigkeit halber :)

Unter Einstellungen > Projekt ist die Einstellung "Kunden E-Mail erforderlich" verfügbar.

Code: https://github.com/OpenOlitor/openolitor-client/commit/8057f35ea955bc6e057226f8a1b50bd574eeb2d7

**Comment by AlwinEgger** [comment]
Danke für die Präzisierung @ideadapt !
