### ISSUE TITLE
Fehler bei Rechnungs-/Berichtserzeugung.

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#50]
Hallo zusammen,
ich weiß leider nicht wohin mit meiner Frage als ein neues Issues zu erstellen.
Ich habe heute die Docker-Container auf den neusten Stand gezogen und wollte einfach nochmal wegen dem erstellen der Rechnung gucken. Ich bekomme selbst beim erstellen eines Datenextrakt jetzt den Fehler: `Bericht konnte nicht erzeugt werden`

![grafik](https://user-images.githubusercontent.com/20152200/107029804-f27abd80-67af-11eb-84a8-30bfebc8ba34.png)

Im log des Servers wird folgendes erzeugt:
`server_1               |  ERROR c.o.core.OpenOlitorExceptionHandler$  - The following Exception was thrown None (of class scala.None$)
`
Wo kann ich das logging erhöhen das ich hier eventuell mehr sehen kann außer die eine Meldung?
Ist das hier meine Anlaufstelle? ` config/server/openolitor-server-logback.xml`
Danke und Gruß
Jan

**Comment by budda85** [comment]
Ich sehe gerade das es in den Zahlungsdetails der Mitglieder eine Änderung bzgl. Datum und Mandats-ID gegeben hat.
Hat das damit zu tun oder gibt es noch mehr Änderungen wo ich eventuell was berücksichtigen muss? Finde sonst nichts anderes was mein Problem sein könnte.
Hier ist das Issue welches ich meine.
#39

**Comment by AlwinEgger** [comment]
Mit der Einführung der QR-Rechnungen in der Schweiz haben wir OpenOlitor mit der Funktion zur Generierung der QR-Codes ergänzt. 

Dazu muss allerdings (im Moment) in den Projekteinstellungen zwingend eine QR-IBAN erfasst werden, auch wenn du diese nicht benötigst. 
![image](https://user-images.githubusercontent.com/4997364/107969361-f8428100-6faf-11eb-8340-795ecba7e46a.png)

Dazu kannst du diese, ungültige IBAN nutzen: `CH44 3199 9123 0008 8901 2`

**Comment by budda85** [comment]
Achso, okay. Dann hatte ich mich von der Fehlermeldung irritieren lassen.
Vorher gab es den Fehler mit der QR-IBAN #49

**Comment by AlwinEgger** [comment]
Ja, die Fehlermeldung ist nicht ok. Der QR-Code muss in Zukunft einfach nicht generiert werden, wenn die IBAN falsch ist.
