### ISSUE TITLE
[Frage] Rechnung an Mitglieder mit Mehrwertsteuer

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#53]
Hallo zusammen,
wir müssen Rechnungen an unsere **Mitglieder** schreiben. Ist es irgendwie möglich das ich den Mehrwertsteuerbetrag auf die Rechnung bekomme?
Formeln sind nicht möglich in einer LibreOffice Vorlage oder?
Bei den Produzenten kann man ja die Mehrwertsteuer Pflicht anhaken, aber Richtung Mitglieder finde ich dazu nichts.
Gruß Jan

**Comment by ClSchreiber** [comment]
Lieber Jan, wir (soliTerre, Bern) schreiben die MWST-Nummer und den Prozentsatz auf jede Rechnung in den Text. Nach CH-Recht reicht das. In DE sollte das bei Kleinbetragsrechnungen auch gehen. Ich kläre das noch wegen Formeln.

**Comment by budda85** [comment]
Hallo Claudia, danke für deine Antwort.
Da wir ein Bieterrunden Prinzip bei uns im Verein haben, hat jedes Mitglied einen anderen Betrag für sein Abo. Somit haben wir leider keinen festen Steuerbetrag den wir einfach auf die Rechnung schreiben könnten.
Um den Aufwand der Rechnungen und vom Steuerberater gering zu halten, wollen wir Dauerrechnungen ausstellen und diese fallen leider nicht unter die Kleinbetragrechnungen :-(

**Comment by GHSGruber** [comment]
Hallo Jan,
wir (sunu-Team) betreuen eine deutsche Hosting-Community für OpenOlitor. Könntest du mir das Rechnungsdokument, so wie es genau ausschauen soll(manuell editiert), mal zukommen lassen. (wolfgang.gruber@sunu.eu)
Meines Wissens gibt es zwei Möglichkeiten, wie man die Steuer ausweisen kann:
Rechnungsnettobetrag     100,00€
zzgl.  19% MWST                      19,00€
Rechnungsbruttobetrag    119,00€
oder:
Rechnungsbruttobetrag     119,00€
Im Rechnungsbetrag sind 19% MWST über 19,00€ enthalten.

Ich würde mich dann mal an LibrOffice versuchen, dies mit Formeln abzubilden.

**Comment by budda85** [comment]
Hallo Wolfgang,
eine richtige Vorlage habe ich aktuell noch nicht erstellt.
Bis jetzt habe ich immer nur mit der Standard-Vorlage "rumgespielt" um das erstellen der Rechnungen zu verstehen. Verstehe ich dich denn richtig, dass ich Formeln in der Libreoffice Vorlage nutzen kann? Mir wäre es egal welche Möglichkeit funktioniert, hauptsache ich bekomme den Steuerbetrag auf die Rechnung :-)

**Comment by budda85** [comment]
Ich hab es geschafft mit den Formeln :-) 
Habe mal meine Vorlage angehängt. Ist zwar noch nicht schön aber es geht. Vielleicht kann es ja jemand gebrauchen.
Das einzige was mich immer noch wundert, ist, dass bei uns im Olitor die Mitglieder mit `Name Vorname` angezeigt werden.
In der Olitor Testumgebung ist es allerdings `Vorname Name`? Wie kann ich das ändern?

[Rechnungsvorlage.zip](https://github.com/OpenOlitor/OpenOlitor/files/6189540/Rechnungsvorlage.zip)

**Comment by GHSGruber** [comment]
Dein Nettobetrag&Steuerbetrag wird vermutlich noch falsch berechnet. Du darfst nicht mit 0,81 multiplizieren sondern musst durch 1,19 dividieren. Der Nettowert ergibt sich dann zu 84,03 und der Steuerbetrag zu 15,97.

**Comment by GHSGruber** [comment]
Die korrrekte Personalisierung mit "Vorname" "Name" in einer Rechnung ist etwas schwierig. Das Feld kunde.bezeichnung wird intern automatisch als "Name"  " Vorname"  gebildet. Du siehst dieses Feld in der Oberfläche gar nicht, solange du nur eine Person als Ansprechpartner definiert hast. Theoretisch könntest du die Personalisierung in der Rechnung über personen.0.vorname und personen.0.name machen. Leider sind aber die Personen nicht in der json für die Rechnung wie im Kundenbrief.
Ein Workaround wäre:
Du legst zunächst eine Dummyperson als zweiten Ansprechpartner an. Wenn du dann in die Mitgliedsdetails gehst, siehst du das Feld kunde.bezeichnung unter "Bezeichnung am Briefkasten", das intern mit "name" "vorname" gebildet wurde und kannst es korrigieren auf "vorname" "name". Danach löscht du den 2. Ansprechpartner wieder und speicherst das Mitglied. 
Der Nachteil hierbei ist, dass
 a) die Übersicht der Mitglieder dann anders sortiert ist, da bei der Mitgliederübersicht das Feld kunde.bezeichnung verwendet wird. 
b) eine erneute Änderung des 1. Ansprechpartners wieder zur automatischen Generierung des Feldes kunde.bezeichnung mit "name" "vorname" führt. 
Warum in der schweizer Demo die Kundenbezeichnung mit "vorname" "name" angezeigt wird, weiß ich nicht. Ich vermute mal, das wurde über SQL geändert. Bei einem Test in der schweizer Testumgebung habe ich scheinbar die Anwendung zum Absturz gebracht. 
@Alwin: Kannst du da mal nachsehen, ich komme nicht mehr in try.openolitor.ch
@Alwin: Könnte man nicht die Personen bei der Rechnung mit in die json aufnehmen, damit eine Personalisierung leichter möglich ist?

**Comment by GHSGruber** [comment]
Hallo Jan,

das Workaround mit dem 2 . Ansprechpartner funkioniert nicht wirklilch nachhaltig. Sobald du erneut das Mitglied aufrufst, und das Mitglied hat nur einen Ansprechpartenr, setzt openOlitor das Feld kunde.bezeichnung wieder auf "name" "vorname" zurück. :-(

**Comment by budda85** [comment]
Hallo Wolfgang, danke für deinen Antworten.
Stimmt, die Formel ist noch Fehlerhaft.
Vielleicht hat Alwin eine Idee was in der schweizer Version anders ist. Da ist es nämlich auch in der json richtig rum mit Vor- und Nachname.

**Comment by alwin** [comment]
Hey all & gutentag, I think you are looking for a different Alwin (different name on Github).

**Comment by GHSGruber** [comment]
Sorry Alwin

**Comment by AlwinEgger** [comment]
Thanks @alwin , yes this handle was already taken somehow :) Please refer to me as @AlwinEgger 

@GHSGruber 
try.openolitor.ch läuft wieder.
Die Personen könnten sicher auch mit geladen werden bei den Rechnungen. Das wäre kein so grosser Change.
Und dann muss ich eine Frage weiterreichen: @mcmpp Did you change something in the german version so Vor- und Nachname are inverse in `kunde.bezeichnung`?

**Comment by alwin** [comment]
> Thanks @alwin , yes this handle was already taken somehow :) Please refer to me as @AlwinEgger
> 
> @GHSGruber
> try.openolitor.ch läuft wieder.
> Die Personen könnten sicher auch mit geladen werden bei den Rechnungen. Das wäre kein so grosser Change.
> Und dann muss ich eine Frage weiterreichen: @mcmpp Did you change something in the german version so Vor- und Nachname are inverse in `kunde.bezeichnung`?

Yeah I was there early so I got the good handle :D Have a nice day!

**Comment by AlwinEgger** [comment]
Wir haben die Lösung auch noch dokumentiert:
https://openolitor.org/mwst-betrag-in-mitgliederrechnung-ausweisen/
