### ISSUE TITLE
Homepage redirecting to delivery-management

### ISSUE THREAD

**Issue by loleg** [OpenOlitor/OpenOlitor#55]
Clicking on the link in the README that looks like it's pointing to the German homepage (http://www.openolitor.org/de/) actually lands me at the subpage https://openolitor.org/delivery-management/

**Comment by mcmpp** [comment]
Thank @loleg  for the feedback. Could you please point me to the place where this link is located? I cannot find this link on the README file. 

Thanks

**Comment by AlwinEgger** [comment]
I guess this was a mistake in the routing on the website. I checked again and there is no such link (any more).
