### ISSUE TITLE
missing translations

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#56]
![image](https://user-images.githubusercontent.com/13901369/118626090-d9c86d80-b7ca-11eb-9cd6-b62d23ffeedb.png)

**Comment by mcmpp** [comment]
![Uploading image.png…]()

**Comment by mcmpp** [comment]
![image](https://user-images.githubusercontent.com/13901369/118628463-e948b600-b7cc-11eb-9cac-6ba64fcaa204.png)

**Comment by mcmpp** [comment]
![image](https://user-images.githubusercontent.com/13901369/118629210-a804d600-b7cd-11eb-88cb-e91f5655d06d.png)

**Comment by mcmpp** [comment]
![image](https://user-images.githubusercontent.com/13901369/118629460-e26e7300-b7cd-11eb-95a0-9f12a680cf9e.png)

**Comment by mcmpp** [comment]
![image](https://user-images.githubusercontent.com/13901369/118630685-0da59200-b7cf-11eb-9834-0b8e041b64d0.png)

**Comment by AlwinEgger** [comment]
Double-Check and if ok, close.

**Comment by ClSchreiber** [comment]
not tested
