### ISSUE TITLE
login page message overflows the frame

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#57]
![image](https://user-images.githubusercontent.com/13901369/118632609-e223a700-b7d0-11eb-95f4-068f7d885ba1.png)

**Comment by mcmpp** [comment]
Changes proposed: 


https://github.com/OpenOlitor/openolitor-client-kundenportal/pull/139
https://github.com/OpenOlitor/openolitor-client-admin/pull/535
https://github.com/OpenOlitor/openolitor-client-core/pull/98

**Comment by ClSchreiber** [comment]
Hoppla, message to be shown before login is not shown before loggin, but very shortly after login, the disappears again....
I had no time to check the frame... (its only shown 2 seconds)
