### ISSUE TITLE
Messages after login overflow the frame. When refreshing, it appears twice

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#58]
![image](https://user-images.githubusercontent.com/13901369/118633082-5eb68580-b7d1-11eb-9151-30c4dc51b96b.png)

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-client-admin/pull/536
https://github.com/OpenOlitor/openolitor-client-core/pull/100

**Comment by ClSchreiber** [comment]
The pop-up "Mitteilung nach dem Login" does not appear after logging in, but "only" with each reload. It cannot process html-code either.
With the field "Benachrichtigung der Kunden", html-Code is correctly displayed (alarm bell)

**Comment by ClSchreiber** [comment]
it does overflow:
![image](https://user-images.githubusercontent.com/15927353/176698651-ad78a23a-0831-465d-8d7b-900eac8d36f9.png)

**Comment by ClSchreiber** [comment]
![image](https://user-images.githubusercontent.com/15927353/176699556-a19abf37-55b8-4b2e-b1a6-6dbfbce27168.png)
