### ISSUE TITLE
Source Code auf Englisch statt Deutsch

### ISSUE THREAD

**Issue by zoosky** [OpenOlitor/OpenOlitor#6]
I should write this in english...

Was waren die Gründe, den Source Code auf Deutsch zu schreiben?

Für Open Source Projekte ist Deutsch/Scala als Programmiersprache ziemlich ungewöhnlich. Ein anderes Projekt, welches auch eine Sprachbarriere aufgebaut hat ist Freedom ERP http://www.freedom.org.br/. Allerdings ist Brasilien etwas grösser als die Schweiz - von wegen Skaleneffekt.

Viele gute Scalaentwickler sprechen zudem französisch...

**Comment by zoosky** [comment]
Selbst das REST API ist auf deutsch..

**Comment by AlwinEgger** [comment]
Nun, wir haben die Erfahrung gemacht, dass in Projekten mit einem Deutsch sprechenden Projektteam und einem mehrheitlich Deutschen Umfeld, das Übersetzen der Entitäten und EST API auf Englisch eher Verwirrung stiftet als es wirklich hilft.
Ist OpenOlitor über ein Erfolg (was wir hoffen) und sollten weitere Entwickler interessiert sein, ist das Übersetzen der Schnittstellen und Entitäten dann rasch gemacht.
