### ISSUE TITLE
Payment details with special chars lead to not-accepted SEPA pain files

### ISSUE THREAD

**Issue by seebi** [OpenOlitor/OpenOlitor#67]
# Problem Description

- If I give the string "Aimée Example" as a Name of account owner, my bank does not accept the resulting PAIN file for direct debit.

# Solution Sketch

There should be a validation for such special chars in this field in order to avoid mistakes.

**Comment by mcmpp** [comment]
Hi @seebi ,

thanks for the feedback! is this only a problem with the Name?? What about of bank name and address??

I am adding a check on this field

**Comment by mcmpp** [comment]
This is the new rule: A-Za-z0-9' . The space is considered. Could you please let me know if this is correct for the bank??

**Comment by mcmpp** [comment]
I have a last proposal. As this issue is only reflected on the sepa document I am going to remove the special characters in the backend. This way, the pdf invoices will have the right spelling. You think this would solve your issue??

**Comment by seebi** [comment]
means "Aimée Example" will be changed to "Aime Example" ?

**Comment by seebi** [comment]
Maybe its just enough to give a warning to the user?

**Comment by mcmpp** [comment]
In Prod
