### ISSUE TITLE
Emails sent from filtered list

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#68]
Reported by Dollinger

have you already seen this behavior (see below)? It's important for us that we can filter the persons to send out emails to relevant people.
### Bug Report
Precondition: just logged in
Actions to Reproduce:
1) go to member->person and apply any filter
2) select a person and apply another filter (best: person selected NOT included)
3) from the new filter, select another person
4) try to send an email from within OpenOlitor
Result: This error test is diplayed: Problem beim Aufruf einer Serverfunktion:
{"cause":"","message":"The request content was malformed:\nUnrecognized baseId format:null"}
Further results: The mail sending function returns same error even if unchecking the persons.
Recover: log out and log in again
Occurance: Systemaic
#/ have you already seen this behavior (see below)? It's important for us that we can filter the persons to send out emails to relevant people.

**Comment by ClSchreiber** [comment]
Oui, la question du choix (cochage) de certaines personnes ou/et abonnements pose parfois des problèmes. je fais toujours un reload F5 avant de continuer, car si non on risque que d'autres données "trainent" avec. Mais je n'ai jamais testé cela à fond, je suis désolée. Mais il y a eu des tickets avant à ce sujet.

**Comment by alexander-nbg** [comment]
Hi Mikel, I just checked on https://try.openolitor.ch in the "Personen" section by:
1) filtered for the three "Vorstandsmiglied" entries and selected all three
2) removed the filter: the right persons from the full list were selected
3) filtered to the one "Goenner" and selected this one
4) removed the filter: only the one "Goenner" is selected
Expected after (4) would be that 4 entries are selected from the filter and selection of (1) and (3). I did not test if the mailing would work despite of this irritating fact display.

The error when trying to send an Email might be gone, but the use case likely does not work yet as expected.

**Comment by mcmpp** [comment]
Hi @alexander-rd,

Thanks for your feedback. I have changed the behavior to cover your expectations. This is still not deployed. If you are happy with this behavior I deploy it in test.

![checkboxes](https://user-images.githubusercontent.com/13901369/167206601-50de0ed7-bba1-4dac-a92f-746bca80d201.gif)

**Comment by alexander-nbg** [comment]
Hi @mcmpp, yes this is what we would expect. Just the mail at the end would come from the custom mail form, not from the option to use the selected emails in whatever email application. But I guess this was just for demonstration that the right addresses were chosen.
For testing: would the public demo instance support enabling mails from the custom email form? Probably not. Then, I would not know how to test this properly.
Thanks!

**Comment by mcmpp** [comment]
Hi @alexander-rd,

as we discussed a few days ago in the meeting I can setup an instance with your data that would allow you to test this feature with the email enabled. In these test instances we enable the email  via a smpt-proxy, mailhog. The emails get capture before they are sent and exposed in a web interface accessible through a port. I contact you via email with the instructions when I have all this setup ready for you.

**Comment by alexander-nbg** [comment]
Hi @mcmpp,

I tested this today with 2.5.4 and the instance you generated for us. It works as expected. Many thanks.

**Comment by ClSchreiber** [comment]
soliTerre-Test: Das Problem ist behoben, wenn die Emailadresse nach dem ersten Filtern "enthäckelt" werden und dann nochmals gefiltert wird.

**Comment by ClSchreiber** [comment]
This cannot be tested without sending emails, tests have to be done in productiv mode as soon as new code is run there
