### ISSUE TITLE
(1) Inaktivierung von Daten

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#69]
Damit OpenOlitor auch über Jahre hinweg gut nutzbar bleibt, sollen Daten inaktiviert werden. Je nach Datentyp geschieht dies automatisch oder selektiv (und somit umkehrbar). 

Für die unten angeführten Datentypen soll eine Inaktivierung eingeführt werden. Auf den entsprechenden Übersichten/Listen wird eine Möglichkeit eingeführt jeweils alle Daten anzuzeigen und somit auch alten Daten zu durchsuchen und wo selektiv möglich auch wieder zu aktivieren.

- [ ] Kunden/Mitglieder - Selektiv: Flag `Inaktiv` auf Detailansicht auswählbar. 
- [ ] Abos: `Laufzeit-Bis` mehr als 6 Monate her
- [ ] Lieferplanungen: Älter als 6 Monate
- [ ] Rechnungen: `Bezahlt` und älter als 6 Monate
- [ ] Einkaufsrechnugnen: `Verrechnet` und älter als 6 Monate
- [ ] Abotypen - Selektiv: Flag `Inaktiv` existiert bereits (wenn Aktiv-Datum abgelaufen); auf Übersicht zur Filterung nutzen
- [ ] Depot-, Tour-, Postauslieferung: `Ausgeliefert` und älter als 6 Monate
- [ ] Arbeitsangebote / Arbeitseinsätze:  `Vergangene` in Filter aufnehmen

#### Bereits existierende Issues zu diesem Thema
 - https://github.com/OpenOlitor/operations/issues/314

---------
_Zu diesem Issue: Zusammen mit den OpenOlitor nutzenden Initiativen möchten wir Details zu möglichen Arbeiten in verschiedenen Bereichen von OpenOlitor erfassen. Alle Interessierten sind eingeladen die oben gemachten Angeben weiter zu verfeinern. Dazu haben wir mehrere [Issues mit dem Label `themensammler`](https://github.com/OpenOlitor/OpenOlitor/labels/themensammler) erstellt._

_Die weiteren Workshops zu Inhalten und Priorisierung sind öffentlich. Lust teilzunehmen? Mail an info(+at+)openolitor.org_

**Comment by SoLaWiD32825** [comment]
Zusätzlich zu den Inaktivierungs- und Selektionsfunktionen wäre die Möglichkeit der endgültigen Löschung eines Datensatzes wichtig. Datenschutzrechtlich ist es m.E. auch nötig, alte Mitgliedsdaten zu entfernen. Wir dürfen Daten ehemaliger Mitglieder nicht endlos lange speichern, sondern müssen sie irgendwann löschen.

Zur einfachen Abfrage/Selektion aktiver Mitglieder: Das wäre prima.
Wir nutzen OO teilweise auch für Mitgliedermails und haben aus diesem Grund aktive Mitglieder zusätzlich "gelabelt" (Mitglieder->Typ). Wir haben unterschiedliche Mitglieds-Labels eingeführt, um pro Versendung über ein Mailprogramm nicht mehr als 50 Adressen zu beschicken. Wir verschicken nicht über Emailformular, weil der eingestellte Absender "noreply-openolitor@sunu.eu" nicht passend ist. Meine Frage in diesem Zusammenhang: Könnte die Funktion "E-Mail versenden an Mitglieder" nicht "Portionen von max. 50 Zieladressen pro Einzelmail" generieren und auf mehrere Mails verteilen? Alternativ wäre super, wenn das Mailformular eine frei definierbare Absendeadresse und die Möglichkeit des Mitverschickens von Dokumenten als Anhang erlauben würde.

**Comment by ClSchreiber** [comment]
Die endgültige Löschung wäre auch so zu erreichen, dass zwar die Datensätze bestehen bleiben (weil eingebunden in Lieferplanungen), dass aber Name, Adresse, etc. durch Zufallsnummern ersetzt werden. Das wäre auch eine Löschung, die rechtlich verhebt.

**Comment by SoLaWiD32825** [comment]
Danke ...  eine hilfreiche "Notlösung"

**Comment by AlwinEgger** [comment]
Einverstanden. Die Details der Mitglieder sollten gelöscht werden können. Zufallsdaten würde ich nicht nehmen, sondern klar definierte Werte wie bspw. `Gelöschte Person`. Diese müssten dann aber auch einen eigenen Status erhalten, so dass sie auf der Übersichtsseiten der `Mitglieder` und `Personen` nie erscheinen.

Um 100% DSGVO konform zu sein, müssten aber auch alle Logs zu dieser Person gelöscht werden. Wir könnten die Events mittels spezifischer Löschung entfernen. Dies würde aber die "theoretische" Möglichkeit ausser Kraft setzen, die DB mittels abspielen aller Events wieder herzustellen. Dies haben wir aber eh nie gemacht.

@SoLaWiD32825 Gegenwärtig könnt ihr die Daten von Hand ersetzen, im Rahmen der Umsetzung der Inaktivierung der Daten würden wir das dann automatisieren.

**Comment by ClSchreiber** [comment]
Zum Emailformular: Es können individuelle Angaben zum zu verwendenden SMTP-Server hinterlegt werden, dann ist der Absender nicht mehr ein "sunu"-Absender, diese Möglichkeit gibt es heute schon. Plus gibt es den OO-Mailserver... Details können wir besprechen.

**Comment by ClSchreiber** [comment]
Mitveschicken als Anhang geht bei Mitgliedern und Rechnungen heute schon, die Dateien müssen vorher hinterlegt werden auf dem S3.

**Comment by SoLaWiD32825** [comment]
S3 heißt: Verwaltung - Report-Vorlagen ?
Email-Formular: würde ich gerne besprechen, auf welchem Weg?

**Comment by ClSchreiber** [comment]
S3 = ein an OO angehängter Speicher
@AlwinEgger kann Dir sagen, an wen Du dich am besten wendest

**Comment by AlwinEgger** [comment]
DSGVO-"Löschung":

- [ ] Auch Löschen von Dateien? (Rechnungen) Was ist mit der Aufbewahrungspflicht?
- [ ] Events (technische Lösung von Tegonal)

**Comment by AlwinEgger** [comment]
Umsetzung nach diversen Diskussionen folgendermassen:

- [X] Kunden - Selektiv: Flag `Inaktiv` auf Detailansicht auswählbar. 
- [X] Abos: Geschäftsjahre-Filter auf Übersicht
- [X] Lieferplanungen: Geschäftsjahre-Filter auf Übersicht
- [X] Rechnungen: Geschäftsjahre-Filter auf Übersicht
- [X] Einkaufsrechnugnen: Geschäftsjahre-Filter auf Übersicht
- [X] Abotypen - Selektiv: Flag `Inaktiv` existiert bereits (wenn Aktiv-Datum abgelaufen); auf Übersicht neu Filter
- [X] Depot-, Tour-, Postauslieferung: Geschäftsjahre-Filter auf Übersicht
- [X] Arbeitsangebote / Arbeitseinsätze:  `Vergangene` in Filter aufgenommen

**Comment by brunnereichhof** [comment]
Die selbe Funktion (Geschäftsjahr) wäre wie bei den Rechnungen auch für die Rechnungspositionen hilfreich.

**Comment by ClSchreiber** [comment]
Kunden - Selektiv: Flag Inaktiv auf Detailansicht auswählbar // Test soliTerre: Deaktivieren führt dazu, dass das Mitglied nicht mehr in der Mitgliederliste aufgeführt wird. Wenn aber das Abo noch läuft, dann werden für das Abo nach wie vor Körbe geplant in den Lieferkommentaren. D.h. diese Aktivierung hat keine Wirkung auf die Laufzeit des Abos, Start und Ende des Abos werden nach wie vor durch das Start- und Ende-Datum des Abos (bei Mitglied) und durch die hinterlegten Lieferdaten gesteuert.

Abos: Geschäftsjahre-Filter auf Übersicht// Test soliTerre: Diese Resultate erscheinen für soliTerre nicht plausibel. Für das GJ 2020/2021 werden bspw. nur 140 Abos angezeigt. Es sind aber mehr als 300 Abos für diese Periode.

**Comment by AlwinEgger** [comment]
Zu 1: Das ist so, wenn ein Kunde archiviert wird, hat dies KEINEN Einfluss auf die Abos! Vorschlag: Falls noch Abos aktiv sind eine entsprechende Warnung vor der Inaktivierung anzeigen.

Zu 2: Überprüfen wir.

**Comment by AlwinEgger** [comment]
Zu 2: Ich erhalte 430 Abos für 20/21:
https://soliterre-test.openolitor.ch/admin/#/abos?q=&g=2020&f=%7B%22zusatzAbosAktiv%22:false%7D&tf=%7B%22abotypId%22:%22%22%7D

![image](https://user-images.githubusercontent.com/4997364/170021749-40b61eaa-bee6-45c4-80d5-f0f782aea6d6.png)


Allerdings gibt es ein Problem bei der Auswahl des Zusatzabos-Filters oben.

**Comment by ClSchreiber** [comment]
![image](https://user-images.githubusercontent.com/15927353/176703503-7069c4da-cdbd-44c7-aee3-0d082f1c77c2.png)
Why do the date lists sometimes go back to years from which no data exist in OO? There can only be data from 2017 onwards, OO did not exist before that... How do we want to solve this?

**Comment by ClSchreiber** [comment]
![image](https://user-images.githubusercontent.com/15927353/176704522-6a127b4d-9206-4138-a3b7-7e6e4bc92405.png)

The year filter is in the subscription overview, but it is not active (because it makes no sense there?)

**Comment by ClSchreiber** [comment]
![image](https://user-images.githubusercontent.com/15927353/176704850-1697bec5-87ce-42b4-905d-bf26e05d0d52.png)
The year filter is in the additional subscription overview, but it is active, but it should always have the default value "all". Does OO or the browser remember this filter when you click backwards and forwards?

**Comment by AlwinEgger** [comment]
> Why do the date lists sometimes go back to years from which no data exist in OO? There can only be data from 2017 onwards, OO did not exist before that... How do we want to solve this?

@ClSchreiber The reason for this: You do have Abos in Soliterre that have a Startdatum back in 1999. This is wrong, but I don't want to correct it by myself. 

BTW: I turned the list around, last year first. Makes more sense.

**Comment by ClSchreiber** [comment]
ah ok, je vais voir..., oui, effectivement, trpo bizzare, je vais laisser ces données, si je sais pourquoi, cela ne me gêne plus
