### ISSUE TITLE
[Fragen] REST-API und Crowdin

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#79]
Ich habe zwei Fragen.

1.  Im Wiki steht, dass es eine REST-API gibt. Kann man die nutzen? Gibt es da eine kleine Doku zu, wie ich mich da zumindest authorisieren kann? Ich würde die gerne probieren zu nutzen bzw. auch dokumentieren.
2. Ich hatte mal im crowdin einen Großteil der deutschen Sprache übersetzt. Im Admin-Teil waren es glaube ich über 90%. Jetzt steht das wieder auf 10%. Wo ist der Rest hin? Wurde das abgelehnt oder eventuell sogar wieder gelöscht?

Gruß, Jan

**Comment by budda85** [comment]
I try it in english :-)

I have two questions.

1. The wiki says that there is a REST API. Is it possible to use it? Is there a small documentation on how I can at least authorize myself? I would like to try to use it and document it.
2. I had once translated a large part of the German language in crowdin. In the admin part, I think it was over 90%. Now it's back to 10%. Where did the rest go? Was that rejected or possibly even deleted again?

Greetings, Jan

**Comment by AlwinEgger** [comment]
Sorry, for the delay.

Yes, there IS a REST API. The web-applications (kundenportal and adminporal) are actually using it for all what they do.
The biggest challenge is, that there is no access-token system in place yet. So you would need to login and fetch a cookie in order to call the API endpoints. And no, there is no documentation so far. I will try to assemble a few hints in the wiki, so you may start. May I ask what your usecase would be?

For the whole question regarding the translation I refer you to @mcmpp He was working on this lately.

**Comment by budda85** [comment]
We had our bidding round in November and we had about 250 individual bids.
You have to manually enter each bid into OO.
The whole bidding round takes quite a bit of volunteer hours ( communications, planning, entering data...)
I wanted to see if I can automate some things and I would rather succeed with the API than learning scala or javascript ;-)

**Comment by mcmpp** [comment]
Hi @budda85 , 

Answering to the second question about the translations. Crowdin released their APIv2 and the integration we had with the APIv1 was not working anymore. I have updated the code to use the APIv2. When I uploaded the files with this new API, crowdin only considered the translations that were different and not all of them. As an example, you can see here how it was for "Abrechen" : 
![image](https://user-images.githubusercontent.com/13901369/150783573-f57a4e04-f93d-43f3-a0cb-0395d3ead81f.png)

And how this is displayed right now. 

![image](https://user-images.githubusercontent.com/13901369/150783652-c5931b07-abc4-4963-9afb-d3528805e6b5.png)

This situation should not break the translations as the similar ones should use the "key"

Does this explanation explain the situation or I am missing something else?? In case you think we should validate more of the strings, please, come back to me and we compare from an old file and replace.
