### ISSUE TITLE
PDF Dokumente zusammenhängen anstatt als ZIP

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#80]
PDF Dokumente sollten als ZIP oder als zusammengehängtes PDF verfügbar sein (wahlweise)

**Comment by mcmpp** [comment]
I have made this change. @ClSchreiber, I would like to introduce the merged pdf instead fo zip as the default behavior but I am not sure on your side if this is a good idea. Could you please advice and contact others if needed??

**Comment by ClSchreiber** [comment]
so default would be merge and zip would be optional? I think thats ok.
What would OO do, if you choose "save pdf-file" and "merge"? that would not be possible, right?

**Comment by mcmpp** [comment]
Hi @ClSchreiber , 

ok, so I am doing this. In case of "save pdf-file" and "merge" OO will create individual files, store them and merge them when downloading.

**Comment by AlwinEgger** [comment]
Test und Rückmeldung von Stefan Brunner:

Am meisten gefreut hat mich die Funktion der Zusammengeführten PDF zb bei den Lieferscheinen :-)

Beim ersten test auf https://brunnereichhof-test.openolitor.ch/admin/#/tourauslieferungen?q=&g=2022&tf=%7B%7D
kam allerdings folgende Fehlermeldung:
 Problem beim Aufruf einer Serverfunktion:

    Der Bericht konnte nicht erzeugt werden:ch.openolitor.core.reporting.ServiceFailed: Vorlage konnte im FileStore nicht gefunden werden: VorlageTourLieferschein, Some(TourLieferschein_Eichhof.odt)


Mit der Standartvorlage wurde zwar ein PDF namens Report_20220424279 generiert und konnte runtergeladen werden.
Jedoch kommt beim versuch das pdf zu öffnen die meldung:
"Beim öffnen dieses Dokuments ist ein Fehler  aufgetreten. Die Datei hat keine Seiten und kann daher nicht geöffnet werden."

**Comment by ClSchreiber** [comment]
Test soliTerre: ZIP Downloads funktioniert mit Standardvorlage bei Mitgliederliste mit 3 ausgewählten Mitgliedern (Brief Mitglied). ZUsammenführen PDFs funktioniert mit 3 ausgewählten Mitgliedern in Firefox. Es folgt eine URL, die kein Dok anzeigt: blob:https://soliterre-test.openolitor.ch/a5910289-2e7c-4b50-97ac-c3b08081e7d2
![grafik](https://user-images.githubusercontent.com/15927353/170023184-a7ed884f-6aa6-493c-9bea-a24a776254a0.png)
In Edge ähnliches Ergebnis:
![grafik](https://user-images.githubusercontent.com/15927353/170023942-9e0b47bc-988a-4c41-801a-79b508455b0f.png)
PDF in Editor geöffnet zeigt folgenden Text an:
%PDF-1.4
%öäüß
1 0 obj
<<
/Type /Catalog
/Version /1.4
/Pages 2 0 R
>>
endobj
2 0 obj
<<
/Type /Pages
/Kids []
/Count 0
>>
endobj
xref
0 3
0000000000 65535 f
0000000015 00000 n
0000000078 00000 n
trailer
<<
/Root 1 0 R
/ID [<8CEA6F24918483849F4303FDF42FE06F> <8CEA6F24918483849F4303FDF42FE06F>]
/Size 3
>>
startxref
130
%%EOF

**Comment by ClSchreiber** [comment]
Test 30.0.2022: same situation as described above
