### ISSUE TITLE
Mitgliederportal: Beitrag "pro ..." streichen da falsch

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#82]
Das Mitgliederportal sollte auch Solidarbeiträge pro Monat anzeigen können (nicht nur pro Lieferung). Es wäre schön, wenn es hier entweder eine Wahlmöglichkeit gäbe, oder die Angabe "pro ..." ganz rausgelassen würde. Ich habe das Problem unter (4) dargestellt. Bislang können wir unseren Mitgliedern im Portal nicht ihren individuellen Mitgliedsbeitrag pro Monat anzeigen, was unbefriedigend ist.

_Originally posted by @SoLaWiD32825 in https://github.com/OpenOlitor/OpenOlitor/issues/77#issuecomment-986709692_

**Comment by ClSchreiber** [comment]
The "Pro" indication is gone and the individual or abotype price is displayed --> OK
