### ISSUE TITLE
Alphabetische Reihenfolge bei den Lieferetiketten stimmt nicht.

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#83]
Alphabetische Reihenfolge bei den Lieferetiketten stimmt nicht.
Alle Namen mit Umlauten kommen ganz am Schluss des entsprechenden Anfangs-Buchstabens (also z.B. Bühler nach Byland). Namen mit von (z.B. von Siebenthal) kommen ganz am Schluss von allen Namen. Schafft Verwirrung in den Depots

_Originally posted by @Mooshof in https://github.com/OpenOlitor/OpenOlitor/issues/77#issuecomment-977865078_

- [ ] This is due to the MariaDB native ordering. We should either reorder the data in Scala OR change the native ordering on the DB (beware of the consequences in searching!)

**Comment by toggm** [comment]
The characterset and collaction could also be set on a query level, maybe that would help:
https://mariadb.com/kb/en/setting-character-sets-and-collations/

But then the collation/characterset needs to be defined per initiative.

**Comment by ClSchreiber** [comment]
is this a good idea? in the past, the way how kunden description has been created by OO was various, once it was Name Vorname, then Vorname Name, if ordered by Vorname Name, this will create more confusion. Or maybe I did not understand the changes that have been made...

**Comment by ClSchreiber** [comment]
@AlwinEgger @mcmpp This is tricky, I am not sure I understand what will happen here in the future with the delivery lists, these lists are important and are used every week, we need to look at this again in detail
