### ISSUE TITLE
Kein Verfall des Links aus der Weblogin Einladung.

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#84]
Kein Verfall des Links aus der Weblogin Einladung.
Den Link welchen wir den NeukundInnen via Weblogin Einladung / Einladung senden" versenden verfällt nach einer gewissen Zeit. So haben wir immer wieder Anfragen von KundInnen, die vergebens versuchen sich einzuloggen. Der Link sollte nicht verfallen.
lg Rebekka

_Originally posted by @Mooshof in https://github.com/OpenOlitor/OpenOlitor/issues/77#issuecomment-977848217_

- [x] Set the value to 180 days

**Comment by mcmpp** [comment]
Extracting this property to the configuration file

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-server/pull/611

**Comment by ClSchreiber** [comment]
i cannot test this function, no access
