### ISSUE TITLE
Lieferplanung: Stepping auf Drei Nachkommastellen bei Gewichten

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#85]
Lieferplanung:
Wir bringen oft bei der Lieferplanung den Betrag nicht korrekt auf "0", weil wir dazu mit 3 Stellen nach dem Komma justieren müssten, das akzeptiert der OpenOlitor aber nicht.
lg Rebekka

_Originally posted by @Mooshof in https://github.com/OpenOlitor/OpenOlitor/issues/77#issuecomment-977853138_

- [x] Weight ajustment step step="0.001"

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-client-admin/pull/563
