### ISSUE TITLE
Mitgliederportal: WYSIWYG für Infos inkl. Zusatzfeld

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#86]
- [x] WYSIWYG Editor für Pre- und Post-Login Infos
- [x] Zusatzfeld für Mitglieder-Infos ganz oben (unabhängig von Lieferinfos) oder Post-Login Info Feld dafür nutzen

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-server/pull/610
https://github.com/OpenOlitor/openolitor-client-core/pull/108
https://github.com/OpenOlitor/openolitor-client-admin/pull/558

resulting on: 

![welcomeMessages](https://user-images.githubusercontent.com/13901369/155334286-50bd3246-acee-457a-b959-ed0edc3f318a.gif)

**Comment by mcmpp** [comment]
https://github.com/OpenOlitor/openolitor-client-kundenportal/pull/151
https://github.com/OpenOlitor/openolitor-client-admin/pull/560
https://github.com/OpenOlitor/openolitor-server/pull/612

**Comment by ClSchreiber** [comment]
Great, but I'm not shure, it seems not to be able to digest html-code:
![image](https://user-images.githubusercontent.com/15927353/176696215-29937ed9-c03a-486b-9d43-14c6be10b0c3.png)
![image](https://user-images.githubusercontent.com/15927353/176696308-eeccbf51-fb8f-4504-849c-47dfe6c76aef.png)
