### ISSUE TITLE
Zahlungsimporten: Book Invoices in Status Erstellt as well

### ISSUE THREAD

**Issue by AlwinEgger** [OpenOlitor/OpenOlitor#87]
Input:

Gut wäre auch ein Dialogfenster, das vor Zahlungsimporten (ESR; CAMT) fragt, ob man die Rechnungen schon auf verschickt gestellt hat. Ein Reminder also, dass im Status Erstellt die Rechnungen nicht abgebucht werden.

_Originally posted by @ClSchreiber in https://github.com/OpenOlitor/OpenOlitor/issues/77#issuecomment-932989853_

Solution:
- [ ] If there is payments referencing Invoices that have not been send, this is obviously a mistake. Also book Rechnungen if in status `Erstellt`

**Comment by ClSchreiber** [comment]
soliTerre Test: Konnte nicht testen, wir haben dazu keine passende Daten. Test erfolgt, sobald in produktiv geschaltet.
