### ISSUE TITLE
Zahlungs-Import: Ergänzungen (1)

### ISSUE THREAD

**Issue by mcmpp** [OpenOlitor/OpenOlitor#89]
- [ ] Link auf Rechnungs-Nr
- Ebenfalls Kunde-Nr ausweisen und verlinken
    - [ ] Datenmodell mit Kundennummer versehen
    - [ ] Auf Frontend anziegen und verlinken
    - [ ] Script erstellen um bestehende Daten zu ergänzen

**Comment by ClSchreiber** [comment]
Test soliTerre: Wenn Status ist "BereitsVerarbeitet", dann führt das Klicken auf Häkchen nicht dazu, dass die Rechnung auf OK gestellt wird. Dito bei Betragnichtkorrekt.

**Comment by ClSchreiber** [comment]
Extremely helpful change! Note: The names come from OO and not from the payment import file, right? Would it be necessary to write this in a tool tip? It could be that another name is in the ESR/CAMT file, i.e. if B has paid in with QR_invoice from A...
