### ISSUE TITLE
DRAFT - Zusatzabos

### ISSUE THREAD

**Issue by toggm** [OpenOlitor/OpenOlitor#9]
**A Beschreibung Funktion**
Beim Import der Daten für Bioabi ist mir aufgefallen, dass sie Supplementäre Abotypen erfasst haben. Dies sind eigentlich Zusatzabos zu bestehenden Abos. Dieser Bedarf wurde auch bereits beim Meeting mit dem Birsmattehof erkannt. Die Idee hierbei wäre, dass auf einem Abotypen zusätzliche Abotypen als Zusatzabos erfasst werden könnten. Diese Zusatzabos müssten aber eine individuelle Laufzeit/Verfügbarkeit haben, damit die Auslieferungen abhängig von dieser Konfiguration erstellt werden könnten. Das Handling betreffend den Lieferdaten müsste noch genauer analysiert werden, da in de meisten Fällen Zusatzabos dieselben Lieferdaten haben wir ihr Hauptabo, andererseits vielleicht zusätzliche Ausnahmen auftreten könnten.
Die Einführung von Zusatzabos hätte folgende Vorteile:
- Gruppieren der Aboauslieferungen (Depot- oder Tourenauslieferung) nach Hauptabo
- Erstellen einer Kundenrechnung, welche das Haupt- und alle Zusatzabos beinhaltet
- Gemeinsames verwalten von Lieferdaten

**B Priorität (hoch, mittel, tief)**
Mittel.

**C Zuordnung zu Modul in OpenOlitor Version 1**
Stammdaten Abotypen

**D Bestehende Abdeckung durch OpenOlitor Version 1**
Abotypen bestehen bereits.

**E Beurteilung / Machbarkeit in OpenOlitor Version 2 (wird von Tegonal GmbH ausgefüllt)**
Stellungnahme Tegonal fehlt noch.

**F Wer ist interessiert? Name Initiative mit Länderangabe**
Bioabi (Schweiz)

**Comment by ClSchreiber** [comment]
Siehe auch Issue "Zusatzbestellungen zu Abos ermöglichen"
https://github.com/OpenOlitor/OpenOlitor/issues/12

**Comment by AlwinEgger** [comment]
In der Zwischenzeit gibt es längst "richtige" Zusatzabos.
