### ISSUE TITLE
unable to compile / run helloworld test

### ISSUE THREAD

**Issue by lamazoni** [OpenOlitor/OpenOlitor#90]
Hello,

... Sorry to post that here but the web portal think I m a bot ....

So here my great experience so far :

1. Download openolitor serveur
https://github.com/OpenOlitor/openolitor-server.git
2. Open it with Intellij IDE
3. Run helloworld test
4. Test fail with :

scalac: Error: Error compiling the sbt component 'compiler-interface-2.11.8-55.0'
sbt.internal.inc.CompileFailed: Error compiling the sbt component 'compiler-interface-2.11.8-55.0'

Regards,

**Comment by AlwinEgger** [comment]
Try it on the console as described here: https://github.com/OpenOlitor/OpenOlitor/wiki/Doku-Technisch_Server_Ent-Setup#server-starten

To start the web-frontend: https://github.com/OpenOlitor/OpenOlitor/wiki/Doku-Technisch_Client_Ent-Setup

**Comment by AlwinEgger** [comment]
@lamazoni Long time ago you asked this question and we didn't get a reaction to our answer. So I close the issue. Please reopen if you need more help.
