### ISSUE TITLE
Reply-to Header für das E-Mail Formular

### ISSUE THREAD

**Issue by budda85** [OpenOlitor/OpenOlitor#94]
Wäre es möglich das E-Mail Formular zu erweitern, um optional eine Reply-To Adresse anzugeben?
Wir haben verschiedene Ansprechpartner bei uns und so könnten die Mitglieder, welche wir über OpenOlitor anschreiben, direkt auf die E-Mail antworten.

**Comment by AlwinEgger** [comment]
Möglich ist dies sicher :)

Da hierfür keine Datenbank-Anpassung notwendig ist, wäre dies auch mit überschaubarem Aufwand umsetzbar. Eine Anpassung auf Client- und Server-Seite ist aber notwendig.

Gutes Issue um sich ein erstes Mal an den Code von OpenOlitor zu wagen.

Ich habe die Anforderung in unser internes [Issue-System](https://scm.tegonal.com/oo/oo-betrieb/-/issues/361) aufgenommen.

**Comment by budda85** [comment]
Hehe,

> Gutes Issue um sich ein erstes Mal an den Code von OpenOlitor zu wagen.

1:0 für dich :-)
Hab ich verstanden und werde es mal probieren.

**Comment by ClSchreiber** [comment]
soliTerre Test: Kann erst im prod System getestet werden (Mailfunktion)
