### ISSUE TITLE
changing the subscription type name does not affect the subscription type name at delivery planing

### ISSUE THREAD

**Issue by JaiDeee** [OpenOlitor/OpenOlitor#96]
**Problem beschreiben / Describe the bug**
If I change the name of my subscription type afterwards, the name does not change at the delivery planing view. The planing still displays the old name. 

**Problem reproduzieren / To Reproduce**

1. - create a new subscription type an call it "TEST"
2. - create a delivery planing for this subscription type
3. - create a new delivery planing and check the name subscription type (should be "TEST")
4. - delete delivery planing
5. - open the subscription type again and change the name to "TEST123"
7. - create a new delivery planing and check the name of subscription type - it is still "TEST"

**Erwartetes Verhalten / Expected behavior**
The name of subscription type should also change at the delivery planing.

**Screenshots**
<img width="1002" alt="Bildschirmfoto 2022-05-15 um 08 15 46" src="https://user-images.githubusercontent.com/105578151/168460129-3343fb7e-b5e8-46d6-94a8-6da73a65d960.png">

**Browser, OS, Version**
 - Browser Safari Version 15.3 (16612.4.9.1.8, 16612)
 - Betriebsystem / OS: MacOS 11.6.4
 - Version UI v2.4.12 (#20210817) / WS v2.4.20 (#20211019)

**Comment by mcmpp** [comment]
Hi @JaiDeee , thanks for your feed back. I am going to have a look into this issue
